import React from "react"
import { LazyPlotly } from "../../../../src/components/Plots"

export default function Ab202516Fig4C4() {
  return (
    <div style={{ clear: "both", marginBottom: "20px" }}>
      <LazyPlotly
        data={[
          {
            error_x: {
              array: {
                dtype: "f8",
                bdata:
                  "UDm0yHa+rz/AoUW28/2kP1A3iUFg5bA/UI2XbhKDwD/gzvdT46WrPwB/arx0k2g/4Pl+arx0kz9ovHSTGAS2P3CR7Xw/Na4/MDMzMzMzsz9IN4lBYOWwP4CVQ4ts57s/wPUoXI/CxT/gehSuR+G6P2A5tMh2vp8/sEkMAiuHpj8gBFYOLbKdP+D5fmq8dJM/QDm0yHa+nz9gvHSTGASmPxAv3SQGgaU/oB6F61G4nj9ovHSTGAS2PzAzMzMzM7M/MIcW2c73oz/Qdr6fGi+tP+D5fmq8dKM/IC/dJAaBlT9A30+Nl26iP2A5tMh2vp8/QN9PjZdukj+QbOf7qfGiP2C8dJMYBKY/ILTIdr6fmj8AqvHSTWKgP4DpJjEIrKw/wB6F61G4nj8AqvHSTWKgPyiHFtnO97M/gEFg5dAiqz+AmZmZmZmZP4DpJjEIrKw/cJHtfD81rj8gL90kBoGlP6CZmZmZmZk/ANejcD0Kpz8gL90kBoGVP9D5fmq8dKM/oPHSTWIQqD8A16NwPQqnP5Bs5/up8aI/0M73U+Olmz/AHoXrUbieP0C0yHa+n4o/aLx0kxgEtj/AHoXrUbieP4AUrkfhepQ/4Pl+arx0oz+AFK5H4XqEP8B2vp8aL60/AH9qvHSTeD9AtMh2vp+aP6Dx0k1iEKg/oJmZmZmZmT9QZDvfT42nP3AUrkfheqQ/ABSuR+F6dD+QbOf7qfGiP9ChRbbz/bQ/0KFFtvP9tD9YuB6F61G4P4DpJjEIrJw/ENejcD0Kpz8AAAAAAAAAAHC8dJMYBKY/8FG4HoXroT9AN4lBYOWgPw==",
              },
              arrayminus: {
                dtype: "f8",
                bdata:
                  "wB6F61G4nj/ASQwCK4emP8ChRbbz/aQ/cGiR7Xw/tT8ABFYOLbKdP4AUrkfhenQ/IARWDi2ynT/Y+X5qvHSzP1AMAiuHFqk/IC/dJAaBpT9Y46WbxCCwP8BJDAIrh7Y/AH9qvHSTuD8wXI/C9SisP0DfT42XbqI/UDeJQWDloD+gxCCwcmihPyAEVg4tsp0/wB6F61G4nj8gL90kBoGVP0C0yHa+n5o/4Pl+arx0kz/wJjEIrByqP9B2vp8aL60/wKFFtvP9pD/gfmq8dJOYPzDfT42XbqI/QDeJQWDloD9g6SYxCKycPzC0yHa+n6o/wB6F61G4nj+QbOf7qfGiP8BJDAIrh6Y/UAwCK4cWqT94FK5H4XqkP1g5tMh2vq8/oMQgsHJooT+QbOf7qfGiP/h+arx0k6g/0KFFtvP9pD+gmZmZmZmZP2CR7Xw/Na4/IIcW2c73oz+w8dJNYhCoP0DfT42XbqI/8CYxCKwcqj9gObTIdr6fP+DO91PjpZs/AH9qvHSTqD9gZDvfT42nP9D5fmq8dKM/gBSuR+F6lD8w30+Nl26SP/B+arx0k5g/lBgEVg4tsj/4qfHSTWKgP2BkO99PjZc/oMQgsHJokT/ASQwCK4eGPyhcj8L1KKw/gBSuR+F6hD+QbOf7qfGiP/BRuB6F66E/AKrx0k1igD9gObTIdr6fP0C0yHa+n6o/gBSuR+F6dD/Adr6fGi+tP+hRuB6F67E/ULgehetRuD9QObTIdr6vP2BkO99PjZc/EC/dJAaBpT8AAAAAAAAAADC0yHa+n6o/UDeJQWDloD+AFK5H4XqkPw==",
              },
              color: "#1f77b4",
              symmetric: false,
              thickness: 1,
              type: "data",
              width: 2,
            },
            hovertemplate: "<b>%{y}</b><br>mean: %{x:.3f}<extra></extra>",
            marker: {
              color: "#1f77b4",
              size: 10,
            },
            mode: "markers",
            name: "Historical",
            opacity: 0.8,
            x: {
              dtype: "f8",
              bdata:
                "SgwCK4cW5T8ZBFYOLbLlPz0K16NwPeY/ZmZmZmZm5j/l0CLb+X7mPzMzMzMzM+c/2/l+arx05z9YObTIdr7nPyuHFtnO9+c/001iEFg56D/6fmq8dJPoP3e+nxov3eg/Gy/dJAaB6T8X2c73U+PpPycxCKwcWuA/pHA9Ctej4D93vp8aL93gPx+F61G4HuE/H4XrUbge4T/y0k1iEFjhP5qZmZmZmeE/RIts5/up4T+YbhKDwMrhP0Jg5dAi2+E/FK5H4XoU4j89CtejcD3iP4/C9Shcj+I/ObTIdr6f4j9iEFg5tMjiPwwCK4cW2eI/YOXQItv54j/+1HjpJjHkP0w3iUFg5eQ/8tJNYhBY5T+8dJMYBFbeP65H4XoUrt8/f2q8dJMY4D/RItv5fmrgP1CNl24Sg+A/JQaBlUOL4D8bL90kBoHhPxBYObTIduI/j8L1KFyP4j+BlUOLbOfjP1TjpZvEIOQ/nu+nxks35T+e76fGSzflPx1aZDvfT+U/Rrbz/dR45T/wp8ZLN4nlPxSuR+F6FOY/cT0K16Nw3T9g5dAi2/neP2Dl0CLb+d4/XrpJDAIr3z8GgZVDi2zfPwRWDi2ynd8/rkfhehSu3z+sHFpkO9/fP9NNYhBYOeA/JQaBlUOL4D+iRbbz/dTgPyGwcmiR7eA/IbByaJHt4D8fhetRuB7hP5qZmZmZmeE/F9nO91Pj4T9oke18PzXiPz0K16NwPeI/5dAi2/l+4j+6SQwCK4fiP7bz/dR46eI/YOXQItv54j81XrpJDALjPwisHFpkO+M/gZVDi2zn4z9I4XoUrkflPw==",
            },
            y: [
              [
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
              ],
              [
                "  กระบี่",
                "  ชุมพร",
                "  นครศรีธรรมราช",
                "  สุราษฎร์ธานี",
                "  พังงา",
                "  ภูเก็ต",
                "  ปัตตานี",
                "  ยะลา",
                "  ระนอง",
                "  นราธิวาส",
                "  ตรัง",
                "  พัทลุง",
                "  สงขลา",
                "  สตูล",
                "  ชัยภูมิ",
                "  ขอนแก่น",
                "  เลย",
                "  หนองบัวลำภู",
                "  มหาสารคาม",
                "  ร้อยเอ็ด",
                "  สุรินทร์",
                "  กาฬสินธุ์",
                "  บุรีรัมย์",
                "  นครราชสีมา",
                "  ศรีสะเกษ",
                "  ยโสธร",
                "  อุดรธานี",
                "  อุบลราชธานี",
                "  อำนาจเจริญ",
                "  บึงกาฬ",
                "  หนองคาย",
                "  สกลนคร",
                "  มุกดาหาร",
                "  นครพนม",
                "  พิจิตร",
                "  นครสวรรค์",
                "  เพชรบูรณ์",
                "  พิษณุโลก",
                "  กำแพงเพชร",
                "  อุทัยธานี",
                "  สุโขทัย",
                "  ตาก",
                "  อุตรดิตถ์",
                "  ลำปาง",
                "  ลำพูน",
                "  น่าน",
                "  แพร่",
                "  พะเยา",
                "  แม่ฮ่องสอน",
                "  เชียงใหม่",
                "  เชียงราย",
                "  อ่างทอง",
                "  นครปฐม",
                "  ปทุมธานี",
                "  พระนครศรีอยุธยา",
                "  นนทบุรี",
                "  ปราจีนบุรี",
                "  นครนายก",
                "  สิงห์บุรี",
                "  สุพรรณบุรี",
                "  สมุทรสาคร",
                "  ชัยนาท",
                "  ฉะเชิงเทรา",
                "  กรุงเทพมหานคร",
                "  กาญจนบุรี",
                "  ลพบุรี",
                "  สมุทรปราการ",
                "  ตราด",
                "  สระแก้ว",
                "  สระบุรี",
                "  ราชบุรี",
                "  จันทบุรี",
                "  ชลบุรี",
                "  สมุทรสงคราม",
                "  เพชรบุรี",
                "  ระยอง",
                "  ประจวบคีรีขันธ์",
              ],
            ],
            type: "scatter",
          },
          {
            error_x: {
              array: {
                dtype: "f8",
                bdata:
                  "kGzn+6nxoj8Af2q8dJOIP8B2vp8aL60/UDeJQWDlsD8AqvHSTWJwPxCsHFpkO68/wEkMAiuHpj+gmZmZmZmZP1A3iUFg5bA/wB6F61G4nj8QrBxaZDuvPwB/arx0k6g/YGQ730+Npz9Y46WbxCCwP6AehetRuJ4/EARWDi2yrT/Adr6fGi+tP5Bs5/up8aI/oJmZmZmZqT9gZDvfT42nP5gYBFYOLbI/0KFFtvP9pD/QoUW28/2kP+D5fmq8dKM/sPHSTWIQqD/QoUW28/2kPzCHFtnO96M/8CYxCKwcqj9ovHSTGAS2P+Clm8QgsLI/qPHSTWIQuD8430+Nl26yPyAv3SQGgZU/8P3UeOkmsT/4qfHSTWKwP/h+arx0k7g/UOOlm8QgsD8Q16NwPQqnP6hwPQrXo7A/wEkMAiuHhj94aJHtfD+1P7Dx0k1iEKg/sPHSTWIQqD/gUbgeheuhP0BkO99PjZc/qHA9CtejsD8gL90kBoGlP+DO91Pjpas/kGzn+6nxoj8Af2q8dJOoP8BJDAIrh5Y/QN9PjZdugj/ASQwCK4eGPyAv3SQGgaU/AKwcWmQ7rz9QN4lBYOWgP9BNYhBYObQ/2Pl+arx0sz8w30+Nl26iP0A3iUFg5aA/AH9qvHSTaD/ASQwCK4eWPyAEVg4tsq0/sJ3vp8ZLtz+gmZmZmZmZPwjXo3A9Crc/AH9qvHSTaD8I16NwPQq3PwAAAAAAAAAAANejcD0Kpz/gzvdT46WrPwCq8dJNYpA/gJVDi2znuz9Ii2zn+6mxP1A3iUFg5aA/sEkMAiuHpj8gXI/C9SisPw==",
              },
              arrayminus: {
                dtype: "f8",
                bdata:
                  "QN9PjZduoj/ASQwCK4eWP3C8dJMYBKY/0E1iEFg5tD8AqvHSTWKQP9DO91Pjpas/gGzn+6nxoj+gmZmZmZmZP1A5tMh2vq8/0KFFtvP9pD+wne+nxku3PwB/arx0k6g/oJmZmZmZqT/AHoXrUbiuP0DfT42XbqI/gOkmMQisnD9QDAIrhxapPwDXo3A9Cqc/AKwcWmQ7rz/wqfHSTWKgPwDXo3A9Cqc/YLx0kxgEpj9w6SYxCKysP/BRuB6F66E/sPHSTWIQqD/QoUW28/2kP8AehetRuJ4/WOOlm8QgsD+o8dJNYhC4P/DSTWIQWLk/mJmZmZmZuT9QN4lBYOWwPyAEVg4tsp0/iMDKoUW2sz+YmZmZmZmpP9z5fmq8dLM/IARWDi2yrT+AbOf7qfGiPwDXo3A9Cqc/wB6F61G4jj8YL90kBoG1PyBcj8L1KKw/0M73U+Olqz/AHoXrUbieP8BJDAIrh5Y/4KWbxCCwsj8gXI/C9SisP1DjpZvEILA/MLTIdr6fqj8Q16NwPQqnP4AUrkfhepQ/AH9qvHSTeD+gSQwCK4eGP9j5fmq8dKM/uB6F61G4rj+UGARWDi2yP4DpJjEIrKw/8CYxCKwcqj8gBFYOLbKtPwB/arx0k6g/AH9qvHSTaD9A6SYxCKyMP+BRuB6F66E/WGQ730+Ntz8gL90kBoGVPwjXo3A9Crc/AKrx0k1iUD+YmZmZmZm5PwAAAAAAAAAAYGQ730+Npz/oUbgeheuxP2BkO99PjZc/MDMzMzMzsz8ArBxaZDuvP6DEILByaKE/0KFFtvP9pD/AHoXrUbiuPw==",
              },
              color: "#d62728",
              symmetric: false,
              thickness: 1,
              type: "data",
              width: 2,
            },
            hovertemplate: "<b>%{y}</b><br>mean: %{x:.3f}<extra></extra>",
            marker: {
              color: "#d62728",
              size: 10,
            },
            mode: "markers",
            name: "Projected",
            opacity: 0.8,
            x: {
              dtype: "f8",
              bdata:
                "JQaBlUOL5D/P91PjpZvkP6AaL90kBuU/aJHtfD815j+PwvUoXI/mP2Q730+Nl+Y/uB6F61G45j+28/3UeOnmPzVeukkMAuc/g8DKoUW25z9YObTIdr7nPwIrhxbZzuc/AiuHFtnO5z8rhxbZzvfnP5qZmZmZmeE/w/UoXI/C4T/sUbgehevhP5HtfD81XuI/ZmZmZmZm4j8QWDm0yHbiP+Olm8QgsOI/N4lBYOXQ4j81XrpJDALjPzEIrBxaZOM/hetRuB6F4z+DwMqhRbbjP6wcWmQ73+M/1XjpJjEI5D8nMQisHFrkP3npJjEIrOQ/eekmMQis5D93vp8aL93kPx1aZDvfT+U/mG4Sg8DK5T8nMQisHFrgP/yp8dJNYuA/HVpkO99P4T+Nl24Sg8DiP2Dl0CLb+eI/NV66SQwC4z+JQWDl0CLjPzMzMzMzM+M/hetRuB6F4z/Jdr6fGi/lP23n+6nx0uU/vHSTGARW5j85tMh2vp/mPw4tsp3vp+Y/N4lBYOXQ5j9WDi2yne/nP3e+nxov3eg/IbByaJHt3D9oke18PzXePwaBlUOLbN8/f2q8dJMY4D8j2/l+arzgP0a28/3UeOE/Rrbz/dR44T8ZBFYOLbLhP+58PzVeuuE/aJHtfD814j/n+6nx0k3iP7x0kxgEVuI/L90kBoGV4z+uR+F6FK7jP6jGSzeJQeQ/0SLb+X5q5D+iRbbz/dTkP0oMAiuHFuU/wcqhRbbz5T/l0CLb+X7mP4ts5/up8eY/NV66SQwC5z8IrBxaZDvnPylcj8L1KOg/I9v5fmq86D/HSzeJQWDpPw==",
            },
            y: [
              [
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
              ],
              [
                "  พังงา",
                "  ภูเก็ต",
                "  กระบี่",
                "  นครศรีธรรมราช",
                "  ปัตตานี",
                "  สงขลา",
                "  สตูล",
                "  ตรัง",
                "  ยะลา",
                "  ชุมพร",
                "  สุราษฎร์ธานี",
                "  พัทลุง",
                "  นราธิวาส",
                "  ระนอง",
                "  ขอนแก่น",
                "  ชัยภูมิ",
                "  หนองบัวลำภู",
                "  ร้อยเอ็ด",
                "  อุดรธานี",
                "  กาฬสินธุ์",
                "  นครราชสีมา",
                "  มหาสารคาม",
                "  เลย",
                "  สกลนคร",
                "  นครพนม",
                "  ยโสธร",
                "  บึงกาฬ",
                "  หนองคาย",
                "  ศรีสะเกษ",
                "  บุรีรัมย์",
                "  สุรินทร์",
                "  มุกดาหาร",
                "  อำนาจเจริญ",
                "  อุบลราชธานี",
                "  นครสวรรค์",
                "  อุทัยธานี",
                "  เพชรบูรณ์",
                "  พิษณุโลก",
                "  อุตรดิตถ์",
                "  สุโขทัย",
                "  ตาก",
                "  กำแพงเพชร",
                "  พิจิตร",
                "  แม่ฮ่องสอน",
                "  แพร่",
                "  น่าน",
                "  ลำปาง",
                "  เชียงใหม่",
                "  ลำพูน",
                "  เชียงราย",
                "  พะเยา",
                "  อ่างทอง",
                "  สิงห์บุรี",
                "  พระนครศรีอยุธยา",
                "  ลพบุรี",
                "  ชัยนาท",
                "  สระบุรี",
                "  สุพรรณบุรี",
                "  ปราจีนบุรี",
                "  นครนายก",
                "  ปทุมธานี",
                "  นนทบุรี",
                "  นครปฐม",
                "  สระแก้ว",
                "  กรุงเทพมหานคร",
                "  ฉะเชิงเทรา",
                "  สมุทรสาคร",
                "  กาญจนบุรี",
                "  สมุทรสงคราม",
                "  สมุทรปราการ",
                "  ตราด",
                "  เพชรบุรี",
                "  ราชบุรี",
                "  ชลบุรี",
                "  ประจวบคีรีขันธ์",
                "  จันทบุรี",
                "  ระยอง",
              ],
            ],
            type: "scatter",
          },
        ]}
        layout={{
          template: {
            data: {
              barpolar: [
                {
                  marker: {
                    line: {
                      color: "white",
                      width: 0.5,
                    },
                    pattern: {
                      fillmode: "overlay",
                      size: 10,
                      solidity: 0.2,
                    },
                  },
                  type: "barpolar",
                },
              ],
              bar: [
                {
                  error_x: {
                    color: "#2a3f5f",
                  },
                  error_y: {
                    color: "#2a3f5f",
                  },
                  marker: {
                    line: {
                      color: "white",
                      width: 0.5,
                    },
                    pattern: {
                      fillmode: "overlay",
                      size: 10,
                      solidity: 0.2,
                    },
                  },
                  type: "bar",
                },
              ],
              carpet: [
                {
                  aaxis: {
                    endlinecolor: "#2a3f5f",
                    gridcolor: "#C8D4E3",
                    linecolor: "#C8D4E3",
                    minorgridcolor: "#C8D4E3",
                    startlinecolor: "#2a3f5f",
                  },
                  baxis: {
                    endlinecolor: "#2a3f5f",
                    gridcolor: "#C8D4E3",
                    linecolor: "#C8D4E3",
                    minorgridcolor: "#C8D4E3",
                    startlinecolor: "#2a3f5f",
                  },
                  type: "carpet",
                },
              ],
              choropleth: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  type: "choropleth",
                },
              ],
              contourcarpet: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  type: "contourcarpet",
                },
              ],
              contour: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  colorscale: [
                    [0.0, "#0d0887"],
                    [0.1111111111111111, "#46039f"],
                    [0.2222222222222222, "#7201a8"],
                    [0.3333333333333333, "#9c179e"],
                    [0.4444444444444444, "#bd3786"],
                    [0.5555555555555556, "#d8576b"],
                    [0.6666666666666666, "#ed7953"],
                    [0.7777777777777778, "#fb9f3a"],
                    [0.8888888888888888, "#fdca26"],
                    [1.0, "#f0f921"],
                  ],
                  type: "contour",
                },
              ],
              heatmap: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  colorscale: [
                    [0.0, "#0d0887"],
                    [0.1111111111111111, "#46039f"],
                    [0.2222222222222222, "#7201a8"],
                    [0.3333333333333333, "#9c179e"],
                    [0.4444444444444444, "#bd3786"],
                    [0.5555555555555556, "#d8576b"],
                    [0.6666666666666666, "#ed7953"],
                    [0.7777777777777778, "#fb9f3a"],
                    [0.8888888888888888, "#fdca26"],
                    [1.0, "#f0f921"],
                  ],
                  type: "heatmap",
                },
              ],
              histogram2dcontour: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  colorscale: [
                    [0.0, "#0d0887"],
                    [0.1111111111111111, "#46039f"],
                    [0.2222222222222222, "#7201a8"],
                    [0.3333333333333333, "#9c179e"],
                    [0.4444444444444444, "#bd3786"],
                    [0.5555555555555556, "#d8576b"],
                    [0.6666666666666666, "#ed7953"],
                    [0.7777777777777778, "#fb9f3a"],
                    [0.8888888888888888, "#fdca26"],
                    [1.0, "#f0f921"],
                  ],
                  type: "histogram2dcontour",
                },
              ],
              histogram2d: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  colorscale: [
                    [0.0, "#0d0887"],
                    [0.1111111111111111, "#46039f"],
                    [0.2222222222222222, "#7201a8"],
                    [0.3333333333333333, "#9c179e"],
                    [0.4444444444444444, "#bd3786"],
                    [0.5555555555555556, "#d8576b"],
                    [0.6666666666666666, "#ed7953"],
                    [0.7777777777777778, "#fb9f3a"],
                    [0.8888888888888888, "#fdca26"],
                    [1.0, "#f0f921"],
                  ],
                  type: "histogram2d",
                },
              ],
              histogram: [
                {
                  marker: {
                    pattern: {
                      fillmode: "overlay",
                      size: 10,
                      solidity: 0.2,
                    },
                  },
                  type: "histogram",
                },
              ],
              mesh3d: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  type: "mesh3d",
                },
              ],
              parcoords: [
                {
                  line: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "parcoords",
                },
              ],
              pie: [
                {
                  automargin: true,
                  type: "pie",
                },
              ],
              scatter3d: [
                {
                  line: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scatter3d",
                },
              ],
              scattercarpet: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scattercarpet",
                },
              ],
              scattergeo: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scattergeo",
                },
              ],
              scattergl: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scattergl",
                },
              ],
              scattermapbox: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scattermapbox",
                },
              ],
              scattermap: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scattermap",
                },
              ],
              scatterpolargl: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scatterpolargl",
                },
              ],
              scatterpolar: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scatterpolar",
                },
              ],
              scatter: [
                {
                  fillpattern: {
                    fillmode: "overlay",
                    size: 10,
                    solidity: 0.2,
                  },
                  type: "scatter",
                },
              ],
              scatterternary: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scatterternary",
                },
              ],
              surface: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  colorscale: [
                    [0.0, "#0d0887"],
                    [0.1111111111111111, "#46039f"],
                    [0.2222222222222222, "#7201a8"],
                    [0.3333333333333333, "#9c179e"],
                    [0.4444444444444444, "#bd3786"],
                    [0.5555555555555556, "#d8576b"],
                    [0.6666666666666666, "#ed7953"],
                    [0.7777777777777778, "#fb9f3a"],
                    [0.8888888888888888, "#fdca26"],
                    [1.0, "#f0f921"],
                  ],
                  type: "surface",
                },
              ],
              table: [
                {
                  cells: {
                    fill: {
                      color: "#EBF0F8",
                    },
                    line: {
                      color: "white",
                    },
                  },
                  header: {
                    fill: {
                      color: "#C8D4E3",
                    },
                    line: {
                      color: "white",
                    },
                  },
                  type: "table",
                },
              ],
            },
            layout: {
              annotationdefaults: {
                arrowcolor: "#2a3f5f",
                arrowhead: 0,
                arrowwidth: 1,
              },
              autotypenumbers: "strict",
              coloraxis: {
                colorbar: {
                  outlinewidth: 0,
                  ticks: "",
                },
              },
              colorscale: {
                diverging: [
                  [0, "#8e0152"],
                  [0.1, "#c51b7d"],
                  [0.2, "#de77ae"],
                  [0.3, "#f1b6da"],
                  [0.4, "#fde0ef"],
                  [0.5, "#f7f7f7"],
                  [0.6, "#e6f5d0"],
                  [0.7, "#b8e186"],
                  [0.8, "#7fbc41"],
                  [0.9, "#4d9221"],
                  [1, "#276419"],
                ],
                sequential: [
                  [0.0, "#0d0887"],
                  [0.1111111111111111, "#46039f"],
                  [0.2222222222222222, "#7201a8"],
                  [0.3333333333333333, "#9c179e"],
                  [0.4444444444444444, "#bd3786"],
                  [0.5555555555555556, "#d8576b"],
                  [0.6666666666666666, "#ed7953"],
                  [0.7777777777777778, "#fb9f3a"],
                  [0.8888888888888888, "#fdca26"],
                  [1.0, "#f0f921"],
                ],
                sequentialminus: [
                  [0.0, "#0d0887"],
                  [0.1111111111111111, "#46039f"],
                  [0.2222222222222222, "#7201a8"],
                  [0.3333333333333333, "#9c179e"],
                  [0.4444444444444444, "#bd3786"],
                  [0.5555555555555556, "#d8576b"],
                  [0.6666666666666666, "#ed7953"],
                  [0.7777777777777778, "#fb9f3a"],
                  [0.8888888888888888, "#fdca26"],
                  [1.0, "#f0f921"],
                ],
              },
              colorway: [
                "#636efa",
                "#EF553B",
                "#00cc96",
                "#ab63fa",
                "#FFA15A",
                "#19d3f3",
                "#FF6692",
                "#B6E880",
                "#FF97FF",
                "#FECB52",
              ],
              font: {
                color: "#2a3f5f",
              },
              geo: {
                bgcolor: "white",
                lakecolor: "white",
                landcolor: "white",
                showlakes: true,
                showland: true,
                subunitcolor: "#C8D4E3",
              },
              hoverlabel: {
                align: "left",
              },
              hovermode: "closest",
              mapbox: {
                style: "light",
              },
              paper_bgcolor: "white",
              plot_bgcolor: "white",
              polar: {
                angularaxis: {
                  gridcolor: "#EBF0F8",
                  linecolor: "#EBF0F8",
                  ticks: "",
                },
                bgcolor: "white",
                radialaxis: {
                  gridcolor: "#EBF0F8",
                  linecolor: "#EBF0F8",
                  ticks: "",
                },
              },
              scene: {
                xaxis: {
                  backgroundcolor: "white",
                  gridcolor: "#DFE8F3",
                  gridwidth: 2,
                  linecolor: "#EBF0F8",
                  showbackground: true,
                  ticks: "",
                  zerolinecolor: "#EBF0F8",
                },
                yaxis: {
                  backgroundcolor: "white",
                  gridcolor: "#DFE8F3",
                  gridwidth: 2,
                  linecolor: "#EBF0F8",
                  showbackground: true,
                  ticks: "",
                  zerolinecolor: "#EBF0F8",
                },
                zaxis: {
                  backgroundcolor: "white",
                  gridcolor: "#DFE8F3",
                  gridwidth: 2,
                  linecolor: "#EBF0F8",
                  showbackground: true,
                  ticks: "",
                  zerolinecolor: "#EBF0F8",
                },
              },
              shapedefaults: {
                line: {
                  color: "#2a3f5f",
                },
              },
              ternary: {
                aaxis: {
                  gridcolor: "#DFE8F3",
                  linecolor: "#A2B1C6",
                  ticks: "",
                },
                baxis: {
                  gridcolor: "#DFE8F3",
                  linecolor: "#A2B1C6",
                  ticks: "",
                },
                bgcolor: "white",
                caxis: {
                  gridcolor: "#DFE8F3",
                  linecolor: "#A2B1C6",
                  ticks: "",
                },
              },
              title: {
                x: 0.05,
              },
              xaxis: {
                automargin: true,
                gridcolor: "#EBF0F8",
                linecolor: "#EBF0F8",
                ticks: "",
                title: {
                  standoff: 15,
                },
                zerolinecolor: "#EBF0F8",
                zerolinewidth: 2,
              },
              yaxis: {
                automargin: true,
                gridcolor: "#EBF0F8",
                linecolor: "#EBF0F8",
                ticks: "",
                title: {
                  standoff: 15,
                },
                zerolinecolor: "#EBF0F8",
                zerolinewidth: 2,
              },
            },
          },
          xaxis: {
            title: {
              font: {
                size: 18,
                color: "black",
              },
              text: "",
            },
            tickfont: {
              size: 16,
              color: "black",
            },
            automargin: true,
          },
          yaxis: {
            title: {
              font: {
                size: 18,
                color: "black",
              },
              text: "",
            },
            tickfont: {
              size: 10,
              color: "black",
            },
            categoryorder: "trace",
            automargin: true,
            domain: [0, 1],
            showgrid: false,
            showdividers: false,
            showline: false,
            ticks: "",
            range: [-0.5, 76.5],
            autorange: false,
          },
          legend: {
            font: {
              size: 18,
              color: "black",
            },
            title: {
              text: "",
            },
            orientation: "h",
            yanchor: "bottom",
            y: 1.0,
            xanchor: "right",
            x: 1,
          },
          plot_bgcolor: "white",
          paper_bgcolor: "white",
          hovermode: "closest",
          shapes: [
            {
              line: {
                color: "darkgrey",
                width: 2,
              },
              opacity: 1,
              type: "line",
              x0: -0.5,
              x1: 1,
              xref: "paper",
              y0: -0.5,
              y1: -0.5,
              yref: "y",
            },
            {
              line: {
                color: "darkgrey",
                width: 2,
              },
              opacity: 1,
              type: "line",
              x0: -0.5,
              x1: 1,
              xref: "paper",
              y0: 13.5,
              y1: 13.5,
              yref: "y",
            },
            {
              line: {
                color: "darkgrey",
                width: 2,
              },
              opacity: 1,
              type: "line",
              x0: -0.5,
              x1: 1,
              xref: "paper",
              y0: 33.5,
              y1: 33.5,
              yref: "y",
            },
            {
              line: {
                color: "darkgrey",
                width: 2,
              },
              opacity: 1,
              type: "line",
              x0: -0.5,
              x1: 1,
              xref: "paper",
              y0: 50.5,
              y1: 50.5,
              yref: "y",
            },
            {
              line: {
                color: "darkgrey",
                width: 2,
              },
              opacity: 1,
              type: "line",
              x0: -0.5,
              x1: 1,
              xref: "paper",
              y0: 76.5,
              y1: 76.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: -0.5,
              y1: 0.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 1.5,
              y1: 2.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 3.5,
              y1: 4.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 5.5,
              y1: 6.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 7.5,
              y1: 8.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 9.5,
              y1: 10.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 11.5,
              y1: 12.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 13.5,
              y1: 14.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 15.5,
              y1: 16.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 17.5,
              y1: 18.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 19.5,
              y1: 20.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 21.5,
              y1: 22.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 23.5,
              y1: 24.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 25.5,
              y1: 26.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 27.5,
              y1: 28.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 29.5,
              y1: 30.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 31.5,
              y1: 32.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 33.5,
              y1: 34.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 35.5,
              y1: 36.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 37.5,
              y1: 38.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 39.5,
              y1: 40.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 41.5,
              y1: 42.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 43.5,
              y1: 44.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 45.5,
              y1: 46.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 47.5,
              y1: 48.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 49.5,
              y1: 50.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 51.5,
              y1: 52.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 53.5,
              y1: 54.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 55.5,
              y1: 56.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 57.5,
              y1: 58.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 59.5,
              y1: 60.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 61.5,
              y1: 62.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 63.5,
              y1: 64.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 65.5,
              y1: 66.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 67.5,
              y1: 68.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 69.5,
              y1: 70.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 71.5,
              y1: 72.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 73.5,
              y1: 74.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 75.5,
              y1: 76.5,
              yref: "y",
            },
          ],
          title: {
            text: "",
          },
          margin: {
            l: 200,
            r: 50,
            t: 50,
            b: 80,
          },
          height: 1200,
          width: 800,
          annotations: [
            {
              align: "center",
              font: {
                color: "black",
                size: 24,
              },
              showarrow: false,
              text: "<b>Idiosyncratic Shock (Mean Absolute)</b>",
              x: 0.28,
              xanchor: "center",
              xref: "paper",
              y: -0.03,
              yanchor: "top",
              yref: "paper",
            },
          ],
        }}
      />
    </div>
  )
}
