import React from "react"
import { LazyPlotly } from "../../../../src/components/Plots"

export default function Ab202516Fig4B4() {
  return (
    <div style={{ clear: "both", marginBottom: "20px" }}>
      <LazyPlotly
        data={[
          {
            error_x: {
              array: {
                dtype: "f8",
                bdata:
                  "6lG4HoX7U0CQwvUoXF9TQFyPwvUojGtAAAAAAACgRkAA16NwPco6QKBwPQrXI0RAYI/C9SjcNUCE61G4HvVQQOB6FK5HgUhA7FG4HoXDYUA8CtejcM1mQHoUrkfh4nNApHA9CtezYkBQuB6F61EwQLgehetR2FFAzMzMzMwsQkAA16NwPQooQLAehetROCtAcD0K16OwOEDYo3A9Ctc7QCpcj8L16FZAWI/C9SicMkCamZmZmdlQQLgehetReDxAaGZmZmamOECcmZmZmXlAQHA9Ctej8C5AIIXrUbheQ0C4HoXrUdhCQOR6FK5HwUJAQArXo3DdQ0BwPQrXo/AjQIjC9ShcjzZAmJmZmZn5U0CgcD0K16MyQKRwPQrXI1ZAhOtRuB7FRkDIzMzMzIw0QJyZmZmZ+UlAANejcD0KGUAYrkfhepQ9QIAUrkfhejlAIIXrUbjePEAI16NwPYo3QCCF61G4PktAuR6F61F4aUDC9Shcj+JWQCpcj8L1WFVAhOtRuB4FZECQwvUoXK9NQJiZmZmZ2V1AgBSuR+F6GkDA9Shcj8IFQCAzMzMzMx9AENejcD2KJEAAKVyPwvX8P6RwPQrX40FAiOtRuB4FNECAZmZmZmYVQEDXo3A9Cg9AYI/C9ShcJEDAzMzMzMwqQKRwPQrXw0RAWLgehesROEBI4XoUroc8QCCF61G4XkBA2KNwPQoXOkAUrkfhesRUQFi4HoXrkTBAAAAAAAAAAAAUrkfherRNQJqZmZmZ6VxAYI/C9ShcM0BQuB6F6/FJQHA9CtejmGNAAAAAAAAATkDqUbgehWtgQA==",
              },
              arrayminus: {
                dtype: "f8",
                bdata:
                  "VLgehetxRUBQuB6F61FDQHoUrkfhOlJAaGZmZmYmOkBUuB6F61FAQMzMzMzMTERAwPUoXI8iQEDE9Shcj2JQQPgoXI/CtURAPgrXo3C9UUB8FK5H4ZpZQGhmZmZmxlhAPArXo3AtXECgR+F6FC4jQFS4HoXr0TZA0KNwPQrXLkAAAAAAAAAcQAAAAAAAACZA6FG4HoWrMkBACtejcL0uQFC4HoXrUT9AwPUoXI/CKEAUrkfhelQ9QJDC9ShcDzRAmJmZmZmZNEAYhetRuN46QBDXo3A9CipAkML1KFwPNUBI4XoUroc0QAAAAAAAQDpA4HoUrkfBQUCwR+F6FC4iQGCPwvUoXDpAxPUoXI8iUEBQuB6F69EtQAAAAAAAwD9A2KNwPQqXPUAAAAAAAIAvQMD1KFyP4kJAwJmZmZmZD0DoUbgehas1QNijcD0K1zBAaGZmZmYmNkCE61G4HgVBQDQzMzMzk0VAUrgeheuBWUCQwvUoXK9NQHA9Ctej0ExAKlyPwvWYU0CYmZmZmVlHQOxRuB6FC1ZAEK5H4XoUFUAgXI/C9SgOQAApXI/C9RZAkML1KFyPGkAAKVyPwvXwP8T1KFyPAjNA8FG4HoXrKkAArkfhehQQQACF61G4Hg9A4HoUrkdhJECAPQrXo3AfQDgzMzMzMztAgOtRuB7FOUDA9Shcj8I9QIjC9ShcjzVAcD0K16OwPUBcj8L1KNxIQPAoXI/CdTJAAAAAAAAAAADgehSuR2FGQOJ6FK5HkVBAULgehetRLkCI61G4HsVPQAAAAAAAIExASOF6FK5nQUB0PQrXo5BaQA==",
              },
              color: "#1f77b4",
              symmetric: false,
              thickness: 1,
              type: "data",
              width: 2,
            },
            hovertemplate: "<b>%{y}</b><br>mean: %{x:.2f}<extra></extra>",
            marker: {
              color: "#1f77b4",
              size: 10,
            },
            mode: "markers",
            name: "Historical",
            opacity: 0.8,
            x: {
              dtype: "f8",
              bdata:
                "zczMzMyEbUC4HoXrUShwQFyPwvUoPHBApHA9Ctf3cEAfhetRuFZxQHsUrkfhVnFA4XoUrkeBcUB7FK5H4apxQJqZmZmZHXNA16NwPQpfc0BSuB6F6211QOxRuB6Fz3VAZmZmZmYueEDXo3A9CgN5QOxRuB6FO2FAMzMzMzNDYUCamZmZmVFhQKRwPQrXg2FAuB6F61HwYUAAAAAAAHhiQI/C9Shcp2JAH4XrUbheY0BSuB6F66ljQFK4HoXrMWRAAAAAAABIZEAUrkfheoxkQKRwPQrX02RAKVyPwvVwZUDD9Shcj/pmQDMzMzMzY2hAMzMzMzPjaED2KFyPwi1qQHsUrkfhYm1A9ihcj8KZcEB7FK5H4cJgQK5H4XoUNmRAhetRuB6NZUBxPQrXoyhmQDMzMzMzg2ZAzczMzMy8ZkAUrkfhetxoQLgehetRAGlAKVyPwvUIaUApXI/C9RhpQOxRuB6F+2lAhetRuB5lbUApXI/C9RhuQClcj8L1sG5ASOF6FK5XcECPwvUoXHdwQKRwPQrX93JAKVyPwvVYXUDXo3A9CpddQOxRuB6FO19ArkfhehTuX0AK16NwPXpgQM3MzMzMtGFA16NwPQrnYUBmZmZmZh5iQD0K16NwTWJA9ihcj8KFYkBxPQrXo5hiQJqZmZmZ4WNA4XoUrkeJZUBcj8L1KDxmQD0K16NwPWZAj8L1KFwPZ0Bcj8L1KBRoQD0K16NwXWhA9ihcj8ItaUCPwvUoXC9pQNejcD0Kz2lArkfhehQGakD2KFyPwiVqQPYoXI/CpWxArkfhehRebkBxPQrXo1R5QA==",
            },
            y: [
              [
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
              ],
              [
                "  สุราษฎร์ธานี",
                "  ตรัง",
                "  กระบี่",
                "  สตูล",
                "  พัทลุง",
                "  ชุมพร",
                "  ปัตตานี",
                "  นครศรีธรรมราช",
                "  นราธิวาส",
                "  ยะลา",
                "  พังงา",
                "  สงขลา",
                "  ระนอง",
                "  ภูเก็ต",
                "  บุรีรัมย์",
                "  ขอนแก่น",
                "  มหาสารคาม",
                "  หนองบัวลำภู",
                "  สุรินทร์",
                "  ร้อยเอ็ด",
                "  นครราชสีมา",
                "  ยโสธร",
                "  ชัยภูมิ",
                "  อุดรธานี",
                "  ศรีสะเกษ",
                "  กาฬสินธุ์",
                "  อำนาจเจริญ",
                "  เลย",
                "  อุบลราชธานี",
                "  สกลนคร",
                "  หนองคาย",
                "  มุกดาหาร",
                "  นครพนม",
                "  บึงกาฬ",
                "  พิจิตร",
                "  นครสวรรค์",
                "  พิษณุโลก",
                "  สุโขทัย",
                "  เพชรบูรณ์",
                "  ลำพูน",
                "  แพร่",
                "  ลำปาง",
                "  พะเยา",
                "  อุตรดิตถ์",
                "  อุทัยธานี",
                "  กำแพงเพชร",
                "  เชียงใหม่",
                "  เชียงราย",
                "  น่าน",
                "  แม่ฮ่องสอน",
                "  ตาก",
                "  ปทุมธานี",
                "  นนทบุรี",
                "  นครปฐม",
                "  กรุงเทพมหานคร",
                "  สมุทรสาคร",
                "  พระนครศรีอยุธยา",
                "  ฉะเชิงเทรา",
                "  อ่างทอง",
                "  สิงห์บุรี",
                "  สมุทรปราการ",
                "  ลพบุรี",
                "  สุพรรณบุรี",
                "  ชัยนาท",
                "  สระบุรี",
                "  สระแก้ว",
                "  ชลบุรี",
                "  ราชบุรี",
                "  ระยอง",
                "  สมุทรสงคราม",
                "  ปราจีนบุรี",
                "  กาญจนบุรี",
                "  เพชรบุรี",
                "  นครนายก",
                "  จันทบุรี",
                "  ประจวบคีรีขันธ์",
                "  ตราด",
              ],
            ],
            type: "scatter",
          },
          {
            error_x: {
              array: {
                dtype: "f8",
                bdata:
                  "MFyPwvVoNkD4KFyPwnVDQEC4HoXr0SxA9ihcj8J9ZUAI16NwPapBQOB6FK5HITZANDMzMzMTVUA0MzMzMzNZQOB6FK5HIUFAxPUoXI9ybEDYo3A9CtdLQLgehetRuGFAgBSuR+F6F0COwvUoXNdgQDAzMzMz8zpAAFK4HoXrF0CwR+F6FK4qQAAAAAAAgDVANDMzMzMTUkCgcD0K16M3QPBRuB6F6z9AuB6F61G4S0DwKFyPwnUqQHwUrkfhWkRAYI/C9ShcJkBI4XoUrudSQMAehetROClAwPUoXI+iQEBQuB6F6/FLQAjXo3A9SjFAmJmZmZmZR0AghetRuN5CQGw9CtejMEdA4HoUrkdBU0DYo3A9CldUQIjrUbgepUBAIIXrUbjOVEBwPQrXo/BLQOB6FK5HIVlAkML1KFyPOEAQrkfhehQxQAAAAAAAIEJADNejcD0KRUDgo3A9Cpc5QLgehetR+EFAaGZmZmYea0CwR+F6FF5YQLgehetRGFJA4HoUrkcRVkDWo3A9CqdjQLgehetRAGZAANajcD0K1z+gmZmZmZklQPAoXI/CNTFAoEfhehSuFEBguB6F61EeQCCuR+F6FBdACNejcD3KP0AYrkfhelQ/QADXo3A9CiJAaGZmZmYmOEDQzMzMzEwyQKRwPQrXY05AWI/C9SjcM0BgPQrXo3AWQIAUrkfhehxAkML1KFwPQUC8HoXrUZhKQITrUbgexU5A4noUrkfxX0AAAAAAAMA0QLgehetR6FVAAAAAAAAAAACE61G4HoVdQDAzMzMzszxAwB6F61H4P0DE9ShcjzJbQA==",
              },
              arrayminus: {
                dtype: "f8",
                bdata:
                  "yMzMzMyMM0AQrkfhehQ4QAApXI/CdS9AcD0K16MQT0C4HoXrURhCQJDC9ShcL0BA6FG4HoWrS0C4HoXrUXhJQChcj8L1SEFAcD0K16PAU0CYmZmZmTlKQAjXo3A9SlRAgJmZmZmZC0DYo3A9CpdcQFC4HoXr0SNAYGZmZmZmE0AAKVyPwvUfQMjMzMzMjDFA6FG4HoVrN0CQwvUoXA8vQIDrUbgeRTdA4HoUrkchQEAghetRuJ4pQOB6FK5HIT1AIFyPwvWoJ0AAAAAAAMA/QKBwPQrXIzVAAAAAAABARUDYo3A9Ctc9QLBH4XoUrixA0MzMzMwMRUCIwvUoXI8zQOxRuB6F60RAAgAAAAAwVEC4HoXrUbg7QKBwPQrXIz5APArXo3DdTEAQrkfhehQ9QHoUrkfhKlBA0MzMzMxMK0CAPQrXo3AdQJDC9ShcDz1A6FG4HoVrRkAwMzMzMzMvQDgK16NwPT5AULgehevBVkDA9Shcj0JPQMzMzMzMDEhAiOtRuB7lSEBSuB6F6/FYQFqPwvUorFhAAK5H4XoU3j9gZmZmZmYfQCCuR+F6lCBAwMzMzMzMGEBA4XoUrkceQHA9Ctej8CRAIIXrUbjeOUAQrkfhepQ3QEAK16NwPSdAaGZmZmZmPECQmZmZmRkmQCCF61G4XkFA8FG4HoXrJ0BgZmZmZmYWQMD1KFyPwhBA4HoUrkfBREBI4XoUrodKQFyPwvUobFJA7FG4HoULT0DAHoXrUbgzQByF61G4vk1AAAAAAAAAAAAAAAAAAABQQEAzMzMzMy5AAAAAAACAMkBI4XoUrsdaQA==",
              },
              color: "#d62728",
              symmetric: false,
              thickness: 1,
              type: "data",
              width: 2,
            },
            hovertemplate: "<b>%{y}</b><br>mean: %{x:.2f}<extra></extra>",
            marker: {
              color: "#d62728",
              size: 10,
            },
            mode: "markers",
            name: "Projected",
            opacity: 0.8,
            x: {
              dtype: "f8",
              bdata:
                "FK5H4XqkbkA9CtejcAVwQMP1KFyPtnBACtejcD0icUAzMzMzM29xQAAAAAAAsHFAMzMzMzPPcUDXo3A9CkdyQAAAAAAA4HJAAAAAAAAkc0B7FK5H4ZJ0QOF6FK5HZXVArkfhehRaeECF61G4HjF5QFK4HoXrEWJAMzMzMzM7YkBSuB6F60liQFyPwvUoXGJAj8L1KFyPY0DNzMzMzJxjQGZmZmZmnmNAexSuR+EqZEAAAAAAADhkQFK4HoXrkWRAhetRuB6tZUB7FK5H4bplQOF6FK5HcWZAmpmZmZm5ZkAfhetRuC5oQNejcD0Kx2hASOF6FK6XaUA9CtejcF1qQM3MzMzMvGpAcT0K16PQcEDXo3A9ChdlQGZmZmZmvmdAXI/C9ShsaUBmZmZmZgZqQLgehetRKGpAexSuR+ECa0BSuB6F62lrQJqZmZmZeW1APQrXo3DlbUBmZmZmZhZuQBSuR+F6ZG5APQrXo3BlcUDhehSuR21xQNejcD0Kl3FAH4XrUbg+c0B7FK5H4ZZzQGZmZmZmdnVAKVyPwvUIYUAAAAAAABBhQOxRuB6FM2FAKVyPwvW4YUBcj8L1KOxhQFyPwvUo5GNA7FG4HoVbZEDhehSuR2FkQKRwPQrXO2VA4XoUrkdhZUBmZmZmZv5lQClcj8L1eGZAcT0K16P4ZkDNzMzMzHRoQK5H4XoUzmhAUrgeheuxakDhehSuRwFtQDMzMzMzo25AMzMzMzMzb0D2KFyPwmVwQGZmZmZminBAH4XrUbgqcUBSuB6F6wVyQPYoXI/CjXRAXI/C9SiwdUAzMzMzMwd7QA==",
            },
            y: [
              [
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
              ],
              [
                "  สตูล",
                "  ตรัง",
                "  พัทลุง",
                "  กระบี่",
                "  สุราษฎร์ธานี",
                "  ปัตตานี",
                "  นครศรีธรรมราช",
                "  ยะลา",
                "  นราธิวาส",
                "  สงขลา",
                "  ชุมพร",
                "  พังงา",
                "  ภูเก็ต",
                "  ระนอง",
                "  ขอนแก่น",
                "  มหาสารคาม",
                "  ร้อยเอ็ด",
                "  หนองบัวลำภู",
                "  นครราชสีมา",
                "  กาฬสินธุ์",
                "  อุดรธานี",
                "  บุรีรัมย์",
                "  ยโสธร",
                "  สุรินทร์",
                "  อำนาจเจริญ",
                "  ชัยภูมิ",
                "  สกลนคร",
                "  ศรีสะเกษ",
                "  เลย",
                "  มุกดาหาร",
                "  หนองคาย",
                "  นครพนม",
                "  อุบลราชธานี",
                "  บึงกาฬ",
                "  นครสวรรค์",
                "  พิจิตร",
                "  อุทัยธานี",
                "  พิษณุโลก",
                "  เพชรบูรณ์",
                "  สุโขทัย",
                "  ลำพูน",
                "  แพร่",
                "  อุตรดิตถ์",
                "  ลำปาง",
                "  พะเยา",
                "  กำแพงเพชร",
                "  เชียงใหม่",
                "  เชียงราย",
                "  แม่ฮ่องสอน",
                "  น่าน",
                "  ตาก",
                "  อ่างทอง",
                "  ลพบุรี",
                "  พระนครศรีอยุธยา",
                "  ปทุมธานี",
                "  สิงห์บุรี",
                "  นนทบุรี",
                "  สระบุรี",
                "  นครปฐม",
                "  ฉะเชิงเทรา",
                "  ชัยนาท",
                "  กรุงเทพมหานคร",
                "  สุพรรณบุรี",
                "  สระแก้ว",
                "  สมุทรปราการ",
                "  สมุทรสาคร",
                "  ชลบุรี",
                "  ปราจีนบุรี",
                "  นครนายก",
                "  กาญจนบุรี",
                "  ระยอง",
                "  ราชบุรี",
                "  สมุทรสงคราม",
                "  จันทบุรี",
                "  เพชรบุรี",
                "  ประจวบคีรีขันธ์",
                "  ตราด",
              ],
            ],
            type: "scatter",
          },
        ]}
        layout={{
          template: {
            data: {
              barpolar: [
                {
                  marker: {
                    line: {
                      color: "white",
                      width: 0.5,
                    },
                    pattern: {
                      fillmode: "overlay",
                      size: 10,
                      solidity: 0.2,
                    },
                  },
                  type: "barpolar",
                },
              ],
              bar: [
                {
                  error_x: {
                    color: "#2a3f5f",
                  },
                  error_y: {
                    color: "#2a3f5f",
                  },
                  marker: {
                    line: {
                      color: "white",
                      width: 0.5,
                    },
                    pattern: {
                      fillmode: "overlay",
                      size: 10,
                      solidity: 0.2,
                    },
                  },
                  type: "bar",
                },
              ],
              carpet: [
                {
                  aaxis: {
                    endlinecolor: "#2a3f5f",
                    gridcolor: "#C8D4E3",
                    linecolor: "#C8D4E3",
                    minorgridcolor: "#C8D4E3",
                    startlinecolor: "#2a3f5f",
                  },
                  baxis: {
                    endlinecolor: "#2a3f5f",
                    gridcolor: "#C8D4E3",
                    linecolor: "#C8D4E3",
                    minorgridcolor: "#C8D4E3",
                    startlinecolor: "#2a3f5f",
                  },
                  type: "carpet",
                },
              ],
              choropleth: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  type: "choropleth",
                },
              ],
              contourcarpet: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  type: "contourcarpet",
                },
              ],
              contour: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  colorscale: [
                    [0.0, "#0d0887"],
                    [0.1111111111111111, "#46039f"],
                    [0.2222222222222222, "#7201a8"],
                    [0.3333333333333333, "#9c179e"],
                    [0.4444444444444444, "#bd3786"],
                    [0.5555555555555556, "#d8576b"],
                    [0.6666666666666666, "#ed7953"],
                    [0.7777777777777778, "#fb9f3a"],
                    [0.8888888888888888, "#fdca26"],
                    [1.0, "#f0f921"],
                  ],
                  type: "contour",
                },
              ],
              heatmap: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  colorscale: [
                    [0.0, "#0d0887"],
                    [0.1111111111111111, "#46039f"],
                    [0.2222222222222222, "#7201a8"],
                    [0.3333333333333333, "#9c179e"],
                    [0.4444444444444444, "#bd3786"],
                    [0.5555555555555556, "#d8576b"],
                    [0.6666666666666666, "#ed7953"],
                    [0.7777777777777778, "#fb9f3a"],
                    [0.8888888888888888, "#fdca26"],
                    [1.0, "#f0f921"],
                  ],
                  type: "heatmap",
                },
              ],
              histogram2dcontour: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  colorscale: [
                    [0.0, "#0d0887"],
                    [0.1111111111111111, "#46039f"],
                    [0.2222222222222222, "#7201a8"],
                    [0.3333333333333333, "#9c179e"],
                    [0.4444444444444444, "#bd3786"],
                    [0.5555555555555556, "#d8576b"],
                    [0.6666666666666666, "#ed7953"],
                    [0.7777777777777778, "#fb9f3a"],
                    [0.8888888888888888, "#fdca26"],
                    [1.0, "#f0f921"],
                  ],
                  type: "histogram2dcontour",
                },
              ],
              histogram2d: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  colorscale: [
                    [0.0, "#0d0887"],
                    [0.1111111111111111, "#46039f"],
                    [0.2222222222222222, "#7201a8"],
                    [0.3333333333333333, "#9c179e"],
                    [0.4444444444444444, "#bd3786"],
                    [0.5555555555555556, "#d8576b"],
                    [0.6666666666666666, "#ed7953"],
                    [0.7777777777777778, "#fb9f3a"],
                    [0.8888888888888888, "#fdca26"],
                    [1.0, "#f0f921"],
                  ],
                  type: "histogram2d",
                },
              ],
              histogram: [
                {
                  marker: {
                    pattern: {
                      fillmode: "overlay",
                      size: 10,
                      solidity: 0.2,
                    },
                  },
                  type: "histogram",
                },
              ],
              mesh3d: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  type: "mesh3d",
                },
              ],
              parcoords: [
                {
                  line: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "parcoords",
                },
              ],
              pie: [
                {
                  automargin: true,
                  type: "pie",
                },
              ],
              scatter3d: [
                {
                  line: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scatter3d",
                },
              ],
              scattercarpet: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scattercarpet",
                },
              ],
              scattergeo: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scattergeo",
                },
              ],
              scattergl: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scattergl",
                },
              ],
              scattermapbox: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scattermapbox",
                },
              ],
              scattermap: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scattermap",
                },
              ],
              scatterpolargl: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scatterpolargl",
                },
              ],
              scatterpolar: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scatterpolar",
                },
              ],
              scatter: [
                {
                  fillpattern: {
                    fillmode: "overlay",
                    size: 10,
                    solidity: 0.2,
                  },
                  type: "scatter",
                },
              ],
              scatterternary: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scatterternary",
                },
              ],
              surface: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  colorscale: [
                    [0.0, "#0d0887"],
                    [0.1111111111111111, "#46039f"],
                    [0.2222222222222222, "#7201a8"],
                    [0.3333333333333333, "#9c179e"],
                    [0.4444444444444444, "#bd3786"],
                    [0.5555555555555556, "#d8576b"],
                    [0.6666666666666666, "#ed7953"],
                    [0.7777777777777778, "#fb9f3a"],
                    [0.8888888888888888, "#fdca26"],
                    [1.0, "#f0f921"],
                  ],
                  type: "surface",
                },
              ],
              table: [
                {
                  cells: {
                    fill: {
                      color: "#EBF0F8",
                    },
                    line: {
                      color: "white",
                    },
                  },
                  header: {
                    fill: {
                      color: "#C8D4E3",
                    },
                    line: {
                      color: "white",
                    },
                  },
                  type: "table",
                },
              ],
            },
            layout: {
              annotationdefaults: {
                arrowcolor: "#2a3f5f",
                arrowhead: 0,
                arrowwidth: 1,
              },
              autotypenumbers: "strict",
              coloraxis: {
                colorbar: {
                  outlinewidth: 0,
                  ticks: "",
                },
              },
              colorscale: {
                diverging: [
                  [0, "#8e0152"],
                  [0.1, "#c51b7d"],
                  [0.2, "#de77ae"],
                  [0.3, "#f1b6da"],
                  [0.4, "#fde0ef"],
                  [0.5, "#f7f7f7"],
                  [0.6, "#e6f5d0"],
                  [0.7, "#b8e186"],
                  [0.8, "#7fbc41"],
                  [0.9, "#4d9221"],
                  [1, "#276419"],
                ],
                sequential: [
                  [0.0, "#0d0887"],
                  [0.1111111111111111, "#46039f"],
                  [0.2222222222222222, "#7201a8"],
                  [0.3333333333333333, "#9c179e"],
                  [0.4444444444444444, "#bd3786"],
                  [0.5555555555555556, "#d8576b"],
                  [0.6666666666666666, "#ed7953"],
                  [0.7777777777777778, "#fb9f3a"],
                  [0.8888888888888888, "#fdca26"],
                  [1.0, "#f0f921"],
                ],
                sequentialminus: [
                  [0.0, "#0d0887"],
                  [0.1111111111111111, "#46039f"],
                  [0.2222222222222222, "#7201a8"],
                  [0.3333333333333333, "#9c179e"],
                  [0.4444444444444444, "#bd3786"],
                  [0.5555555555555556, "#d8576b"],
                  [0.6666666666666666, "#ed7953"],
                  [0.7777777777777778, "#fb9f3a"],
                  [0.8888888888888888, "#fdca26"],
                  [1.0, "#f0f921"],
                ],
              },
              colorway: [
                "#636efa",
                "#EF553B",
                "#00cc96",
                "#ab63fa",
                "#FFA15A",
                "#19d3f3",
                "#FF6692",
                "#B6E880",
                "#FF97FF",
                "#FECB52",
              ],
              font: {
                color: "#2a3f5f",
              },
              geo: {
                bgcolor: "white",
                lakecolor: "white",
                landcolor: "white",
                showlakes: true,
                showland: true,
                subunitcolor: "#C8D4E3",
              },
              hoverlabel: {
                align: "left",
              },
              hovermode: "closest",
              mapbox: {
                style: "light",
              },
              paper_bgcolor: "white",
              plot_bgcolor: "white",
              polar: {
                angularaxis: {
                  gridcolor: "#EBF0F8",
                  linecolor: "#EBF0F8",
                  ticks: "",
                },
                bgcolor: "white",
                radialaxis: {
                  gridcolor: "#EBF0F8",
                  linecolor: "#EBF0F8",
                  ticks: "",
                },
              },
              scene: {
                xaxis: {
                  backgroundcolor: "white",
                  gridcolor: "#DFE8F3",
                  gridwidth: 2,
                  linecolor: "#EBF0F8",
                  showbackground: true,
                  ticks: "",
                  zerolinecolor: "#EBF0F8",
                },
                yaxis: {
                  backgroundcolor: "white",
                  gridcolor: "#DFE8F3",
                  gridwidth: 2,
                  linecolor: "#EBF0F8",
                  showbackground: true,
                  ticks: "",
                  zerolinecolor: "#EBF0F8",
                },
                zaxis: {
                  backgroundcolor: "white",
                  gridcolor: "#DFE8F3",
                  gridwidth: 2,
                  linecolor: "#EBF0F8",
                  showbackground: true,
                  ticks: "",
                  zerolinecolor: "#EBF0F8",
                },
              },
              shapedefaults: {
                line: {
                  color: "#2a3f5f",
                },
              },
              ternary: {
                aaxis: {
                  gridcolor: "#DFE8F3",
                  linecolor: "#A2B1C6",
                  ticks: "",
                },
                baxis: {
                  gridcolor: "#DFE8F3",
                  linecolor: "#A2B1C6",
                  ticks: "",
                },
                bgcolor: "white",
                caxis: {
                  gridcolor: "#DFE8F3",
                  linecolor: "#A2B1C6",
                  ticks: "",
                },
              },
              title: {
                x: 0.05,
              },
              xaxis: {
                automargin: true,
                gridcolor: "#EBF0F8",
                linecolor: "#EBF0F8",
                ticks: "",
                title: {
                  standoff: 15,
                },
                zerolinecolor: "#EBF0F8",
                zerolinewidth: 2,
              },
              yaxis: {
                automargin: true,
                gridcolor: "#EBF0F8",
                linecolor: "#EBF0F8",
                ticks: "",
                title: {
                  standoff: 15,
                },
                zerolinecolor: "#EBF0F8",
                zerolinewidth: 2,
              },
            },
          },
          xaxis: {
            title: {
              font: {
                size: 18,
                color: "black",
              },
              text: "",
            },
            tickfont: {
              size: 16,
              color: "black",
            },
            automargin: true,
          },
          yaxis: {
            title: {
              font: {
                size: 18,
                color: "black",
              },
              text: "",
            },
            tickfont: {
              size: 10,
              color: "black",
            },
            categoryorder: "trace",
            automargin: true,
            domain: [0, 1],
            showgrid: false,
            showdividers: false,
            showline: false,
            ticks: "",
            range: [-0.5, 76.5],
            autorange: false,
          },
          legend: {
            font: {
              size: 18,
              color: "black",
            },
            title: {
              text: "",
            },
            orientation: "h",
            yanchor: "bottom",
            y: 1.0,
            xanchor: "right",
            x: 1,
          },
          plot_bgcolor: "white",
          paper_bgcolor: "white",
          hovermode: "closest",
          shapes: [
            {
              line: {
                color: "darkgrey",
                width: 2,
              },
              opacity: 1,
              type: "line",
              x0: -0.5,
              x1: 1,
              xref: "paper",
              y0: -0.5,
              y1: -0.5,
              yref: "y",
            },
            {
              line: {
                color: "darkgrey",
                width: 2,
              },
              opacity: 1,
              type: "line",
              x0: -0.5,
              x1: 1,
              xref: "paper",
              y0: 13.5,
              y1: 13.5,
              yref: "y",
            },
            {
              line: {
                color: "darkgrey",
                width: 2,
              },
              opacity: 1,
              type: "line",
              x0: -0.5,
              x1: 1,
              xref: "paper",
              y0: 33.5,
              y1: 33.5,
              yref: "y",
            },
            {
              line: {
                color: "darkgrey",
                width: 2,
              },
              opacity: 1,
              type: "line",
              x0: -0.5,
              x1: 1,
              xref: "paper",
              y0: 50.5,
              y1: 50.5,
              yref: "y",
            },
            {
              line: {
                color: "darkgrey",
                width: 2,
              },
              opacity: 1,
              type: "line",
              x0: -0.5,
              x1: 1,
              xref: "paper",
              y0: 76.5,
              y1: 76.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: -0.5,
              y1: 0.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 1.5,
              y1: 2.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 3.5,
              y1: 4.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 5.5,
              y1: 6.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 7.5,
              y1: 8.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 9.5,
              y1: 10.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 11.5,
              y1: 12.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 13.5,
              y1: 14.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 15.5,
              y1: 16.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 17.5,
              y1: 18.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 19.5,
              y1: 20.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 21.5,
              y1: 22.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 23.5,
              y1: 24.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 25.5,
              y1: 26.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 27.5,
              y1: 28.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 29.5,
              y1: 30.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 31.5,
              y1: 32.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 33.5,
              y1: 34.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 35.5,
              y1: 36.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 37.5,
              y1: 38.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 39.5,
              y1: 40.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 41.5,
              y1: 42.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 43.5,
              y1: 44.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 45.5,
              y1: 46.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 47.5,
              y1: 48.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 49.5,
              y1: 50.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 51.5,
              y1: 52.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 53.5,
              y1: 54.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 55.5,
              y1: 56.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 57.5,
              y1: 58.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 59.5,
              y1: 60.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 61.5,
              y1: 62.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 63.5,
              y1: 64.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 65.5,
              y1: 66.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 67.5,
              y1: 68.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 69.5,
              y1: 70.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 71.5,
              y1: 72.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 73.5,
              y1: 74.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 75.5,
              y1: 76.5,
              yref: "y",
            },
          ],
          title: {
            text: "",
          },
          margin: {
            l: 200,
            r: 50,
            t: 50,
            b: 80,
          },
          height: 1200,
          width: 800,
          annotations: [
            {
              align: "center",
              font: {
                color: "black",
                size: 24,
              },
              showarrow: false,
              text: "<b>Idiosyncratic Shock (Mean Absolute)</b>",
              x: 0.28,
              xanchor: "center",
              xref: "paper",
              y: -0.03,
              yanchor: "top",
              yref: "paper",
            },
          ],
        }}
      />
    </div>
  )
}
