import React from "react"
import { LazyPlotly } from "../../../../src/components/Plots"

export default function Ab202516Fig4A1() {
  return (
    <div style={{ clear: "both", marginBottom: "20px" }}>
      <LazyPlotly
        data={[
          {
            error_x: {
              array: {
                dtype: "f8",
                bdata:
                  "IIXrUbge5T/Ao3A9CtfjP4AUrkfheuQ/4HoUrkfh6j/Ao3A9CtfTP+B6FK5H4eI/INejcD0K7z9gZmZmZmbyP8D1KFyPwv0/4Chcj8L16D9Aj8L1KFznPxCuR+F6FPY/gHA9Ctej0D8AIIXrUbiePyAK16NwPeo/YGZmZmZm5j+AmZmZmZnJPwAAAAAAANA/gML1KFyP0j8AXI/C9Si8PwCF61G4HtU/AKRwPQrX0z/A61G4HoXbP8CjcD0K19M/QOF6FK5H0T8AXI/C9SjMPwB7FK5H4co/AB+F61G4zj8A16NwPQrHPwAfhetRuL4/APYoXI/CxT+AHoXrUbjOPwBcj8L1KLw/AB+F61G4vj+AFK5H4XrsP+hRuB6F6wFAkML1KFyP8j9wFK5H4Xr8P2CPwvUoXO8/QFyPwvUo5D/gKFyPwvXgP0Bcj8L1KOw/wKNwPQrX0z8Q16NwPQr3P4AUrkfhevg/cGZmZmZm8j8ghetRuB7xPwApXI/C9fA/gJmZmZmZ2T/gKFyPwvXgP4CZmZmZmck/kJmZmZmZ9T8AAAAAAADgP0AK16NwPeo/APYoXI/CxT/AcD0K16PQP2CPwvUoXOc/oHA9Ctej6D+AFK5H4XrkP6BwPQrXo+A/oJmZmZmZ4T8AKVyPwvXgPwApXI/C9eA/wKNwPQrX0z8AAAAAAAAAAAD2KFyPwsU/ALgehetRyD8AXY/C9Si8PwBcj8L1KLw/wFG4HoXr0T8AexSuR+HKPwCZmZmZmbk/AFK4HoXrsT8AIIXrUbiuPwAUrkfhepQ/ABCuR+F6hD8AHoXrUbiuPw==",
              },
              arrayminus: {
                dtype: "f8",
                bdata:
                  "QArXo3A94j8AAAAAAADoP8B6FK5H4do/IIXrUbge5T/Ao3A9CtfTP1DhehSuR/U/EK5H4XoU8j9ACtejcD3iP8DMzMzMzOw/QFyPwvUo5D+AZmZmZmbmP7AehetRuPI/AClcj8L16D8AmpmZmZmpP/BRuB6F6/E/4HoUrkfh+j8AuB6F61HIP8DC9Shcj9I/gI/C9Shc3z8A16NwPQrHP0DXo3A9Ctc/gJmZmZmZ2T+QmZmZmZnxPwCF61G4HtU/gJmZmZmZ2T9guB6F61HoPwB7FK5H4co/wKNwPQrX0z9AuB6F61HYPwDXo3A9Crc/wPUoXI/C1T/AwvUoXI/SPwAfhetRuL4/gB6F61G4zj+wHoXrUbjyPxCuR+F6FP4/MDMzMzMz/z+APQrXo3D9PyCF61G4HvU/4HoUrkfh6j9g4XoUrkfhP+B6FK5H4fI/gBSuR+F61D+A61G4HoX7PzBcj8L1KPg/WI/C9ShcAUDwUbgehesDQEAK16NwPf4/4KNwPQrX4z/wUbgehev1PwApXI/C9eA/iOtRuB6FA0CgmZmZmZnhP6CZmZmZmeE/AIXrUbge1T9AuB6F61HYP7AehetRuP4/oB6F61G45j+gcD0K16P8P6BH4XoUruc/oHA9Ctej4D9Aj8L1KFzvP6BH4XoUru8/AIXrUbge1T8AAAAAAAAAAEAK16NwPeI/oOtRuB6F4z8AUbgeheuxPwCF61G4HtU/wML1KFyP0j9AMzMzMzPTP4C4HoXrUdg/gPUoXI/CxT8AHoXrUbiuPwAghetRuJ4/AAAAAAAAAAAAFa5H4Xq0Pw==",
              },
              color: "#1f77b4",
              symmetric: false,
              thickness: 1,
              type: "data",
              width: 2,
            },
            hovertemplate: "<b>%{y}</b><br>mean: %{x:.2f}<extra></extra>",
            marker: {
              color: "#1f77b4",
              size: 10,
            },
            mode: "markers",
            name: "Historical",
            opacity: 0.8,
            x: {
              dtype: "f8",
              bdata:
                "cT0K16PwN0D2KFyPwvU3QArXo3A9CjhApHA9CtcjOECuR+F6FG44QM3MzMzMjDhAj8L1KFyPOEAfhetRuJ44QClcj8L1qDhA7FG4HoWrOEDsUbgehes4QFyPwvUoXDlAUrgeheuROUB7FK5H4bo6QMP1KFyPQjZAXI/C9SjcNkDhehSuRyE3QMP1KFyPQjdASOF6FK5HN0DNzMzMzEw3QJqZmZmZWTdAMzMzMzNzN0A9CtejcH03QAAAAAAAgDdAhetRuB6FN0BI4XoUroc3QPYoXI/CtTdAhetRuB7FN0DNzMzMzMw3QI/C9ShczzdAFK5H4XrUN0BxPQrXo/A3QPYoXI/C9TdAuB6F61H4N0DhehSuR+EzQAAAAAAAgDRAhetRuB4FNUDsUbgehWs1QNejcD0KlzVAFK5H4XoUNkAfhetRuB42QI/C9ShcTzZAmpmZmZmZNkDXo3A9Chc3QAAAAAAAQDdAMzMzMzPzN0BI4XoUrgc4QArXo3A9CjhAzczMzMyMOEAfhetRuJ44QEjhehSuBzlAmpmZmZmZN0DsUbgehas3QPYoXI/CtTdAZmZmZmYmOEC4HoXrUTg4QD0K16NwPThAj8L1KFxPOEBcj8L1KFw4QK5H4XoUbjhA9ihcj8J1OEAUrkfhepQ4QK5H4XoUrjhAAAAAAADAOEAzMzMzM/M4QAAAAAAAADlAw/UoXI8COUAUrkfhehQ5QNejcD0KFzlAmpmZmZkZOUBcj8L1KBw5QB+F61G4HjlAZmZmZmYmOUBmZmZmZiY5QK5H4XoULjlAcT0K16MwOUDD9Shcj0I5QA==",
            },
            y: [
              [
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
              ],
              [
                "  ระนอง",
                "  ยะลา",
                "  ชุมพร",
                "  สุราษฎร์ธานี",
                "  ตรัง",
                "  นราธิวาส",
                "  นครศรีธรรมราช",
                "  กระบี่",
                "  พังงา",
                "  สตูล",
                "  พัทลุง",
                "  สงขลา",
                "  ปัตตานี",
                "  ภูเก็ต",
                "  เลย",
                "  ชัยภูมิ",
                "  มุกดาหาร",
                "  นครพนม",
                "  สกลนคร",
                "  หนองบัวลำภู",
                "  บึงกาฬ",
                "  อุดรธานี",
                "  นครราชสีมา",
                "  กาฬสินธุ์",
                "  หนองคาย",
                "  ขอนแก่น",
                "  อำนาจเจริญ",
                "  ยโสธร",
                "  บุรีรัมย์",
                "  มหาสารคาม",
                "  ร้อยเอ็ด",
                "  อุบลราชธานี",
                "  สุรินทร์",
                "  ศรีสะเกษ",
                "  แม่ฮ่องสอน",
                "  เชียงใหม่",
                "  น่าน",
                "  ตาก",
                "  เชียงราย",
                "  พะเยา",
                "  ลำพูน",
                "  ลำปาง",
                "  แพร่",
                "  เพชรบูรณ์",
                "  อุตรดิตถ์",
                "  พิษณุโลก",
                "  กำแพงเพชร",
                "  อุทัยธานี",
                "  สุโขทัย",
                "  นครสวรรค์",
                "  พิจิตร",
                "  กาญจนบุรี",
                "  จันทบุรี",
                "  ประจวบคีรีขันธ์",
                "  ตราด",
                "  สระแก้ว",
                "  เพชรบุรี",
                "  นครนายก",
                "  ราชบุรี",
                "  ระยอง",
                "  ลพบุรี",
                "  ปราจีนบุรี",
                "  สระบุรี",
                "  ชลบุรี",
                "  สมุทรสงคราม",
                "  ฉะเชิงเทรา",
                "  สุพรรณบุรี",
                "  ชัยนาท",
                "  ปทุมธานี",
                "  สมุทรปราการ",
                "  กรุงเทพมหานคร",
                "  นนทบุรี",
                "  พระนครศรีอยุธยา",
                "  นครปฐม",
                "  สิงห์บุรี",
                "  อ่างทอง",
                "  สมุทรสาคร",
              ],
            ],
            type: "scatter",
          },
          {
            error_x: {
              array: {
                dtype: "f8",
                bdata:
                  "oML1KFyP4j/gehSuR+HiP+DMzMzMzOQ/oOtRuB6F6z+AFK5H4XrUP+B6FK5H4eI/IK5H4XoU7j8wXI/C9SjwP8AehetRuPo/AClcj8L16D9gj8L1KFznP2CPwvUoXPM/wHA9Ctej0D8AFK5H4XqkP+B6FK5H4eo/YGZmZmZm5j8AuB6F61HIP4BwPQrXo9A/wML1KFyP0j8AXI/C9Si8P0CF61G4HtU/wKNwPQrX0z/A61G4HoXbP8CjcD0K19M/AFyPwvUozD9A4XoUrkfRP4A9CtejcM0/ANejcD0Kxz8AAAAAAADQP4BwPQrXo8A/ANejcD0Kxz+APQrXo3DNPwAfhetRuL4/AB+F61G4vj8gXI/C9SjsPxiuR+F6FAJAcGZmZmZm8j/QzMzMzMz8P2CPwvUoXO8/wMzMzMzM5D+gmZmZmZnhP4AUrkfheuw/AKRwPQrX0z/AHoXrUbj2P6BwPQrXo/g/kML1KFyP8j9A4XoUrkfxP9DMzMzMzPA/QArXo3A92j8AKVyPwvXgPwCamZmZmck/QK5H4XoU3j+gmZmZmZn1P+B6FK5H4eo/gBSuR+F6xD+gR+F6FK7nPwAAAAAAANA/QOF6FK5H6T+AFK5H4XrkP2DhehSuR+E/QOF6FK5H4T8AKVyPwvXgP+AoXI/C9eA/AKRwPQrX0z8AAAAAAAAAAAD2KFyPwsU/gLgehetRyD+AwvUoXI/SP4CZmZmZmck/AJqZmZmZuT8AXI/C9Si8PwBcj8L1KLw/ANejcD0Ktz8AmJmZmZmpPwAUrkfhepQ/ABCuR+F6hD8AmJmZmZmpPw==",
              },
              arrayminus: {
                dtype: "f8",
                bdata:
                  "QOF6FK5H4T9gj8L1KFznP8B6FK5H4do/YBSuR+F65D8ApHA9CtfTPwApXI/C9fQ/kJmZmZmZ8T+gmZmZmZnhP+B6FK5H4eo/gOtRuB6F4z9gPQrXo3DlP1DhehSuR/E/oJmZmZmZ6T8AmpmZmZmpP5DC9Shcj/I/YI/C9Shc+z8AmpmZmZnJP0AzMzMzM9M/QI/C9Shc3z8A16NwPQrHPwDXo3A9Ctc/QLgehetR2D/gUbgehevxPwCF61G4HtU/oHA9Ctej6D/AKFyPwvXYP4B6FK5H4co/wChcj8L12D+AFK5H4XrUPwDXo3A9Crc/wPUoXI/C1T+AwvUoXI/SPwAehetRuL4/gD0K16NwzT9wZmZmZmbyP0AK16NwPf4/ANejcD0K/z9wPQrXo3D9PyCF61G4HvU/QDMzMzMz6z+gmZmZmZnhP7AehetRuPI/AIXrUbge1T8wMzMzMzP7PyBcj8L1KPg/cD0K16NwAUDwUbgehesDQEAK16NwPf4/QFyPwvUo5D/A9Shcj8L1P4CZmZmZmeE/4FG4HoXr4T+YmZmZmZkDQKDC9Shcj+I/wKNwPQrX0z+QwvUoXI/+P0C4HoXrUdg/wB6F61G45j+AFK5H4Xr8P6BwPQrXo+g/wHA9Ctej4D+gR+F6FK7vP2CPwvUoXO8/wKNwPQrX0z8AAAAAAAAAAOBRuB6F6+E/gOtRuB6F4z/AwvUoXI/SP4AUrkfhetQ/wPUoXI/C1T8AFK5H4Xq0P8BH4XoUrtc/gPUoXI/CxT8AmpmZmZmpPwAUrkfhepQ/AAAAAAAAAAAA16NwPQq3Pw==",
              },
              color: "#d62728",
              symmetric: false,
              thickness: 1,
              type: "data",
              width: 2,
            },
            hovertemplate: "<b>%{y}</b><br>mean: %{x:.2f}<extra></extra>",
            marker: {
              color: "#d62728",
              size: 10,
            },
            mode: "markers",
            name: "Projected",
            opacity: 0.8,
            x: {
              dtype: "f8",
              bdata:
                "XI/C9ShcOUDhehSuR2E5QLgehetReDlAFK5H4XqUOUCamZmZmdk5QOxRuB6F6zlAMzMzMzPzOUCF61G4HgU6QArXo3A9CjpAFK5H4XoUOkAK16NwPUo6QPYoXI/CtTpAMzMzMzPzOkDsUbgehes7QIXrUbgexTdA16NwPQpXOEDsUbgehas4QEjhehSuxzhAj8L1KFzPOEDXo3A9Ctc4QFyPwvUo3DhAexSuR+H6OEA9CtejcP04QIXrUbgeBTlAzczMzMwMOUCPwvUoXA85QD0K16NwPTlAj8L1KFxPOUCPwvUoXE85QFK4HoXrUTlAXI/C9ShcOUC4HoXrUXg5QD0K16NwfTlAhetRuB6FOUAfhetRuF41QAAAAAAAADZAPQrXo3B9NkAfhetRuN42QNejcD0KFzdAUrgeheuRN0AfhetRuJ43QArXo3A9yjdAj8L1KFwPOEAK16NwPYo4QDMzMzMzszhAZmZmZmZmOUDD9Shcj4I5QIXrUbgehTlASOF6FK4HOkDXo3A9Chc6QD0K16NwfTpAj8L1KFwPOUCPwvUoXA85QB+F61G4HjlACtejcD2KOUApXI/C9ag5QK5H4XoUrjlA9ihcj8K1OUDNzMzMzMw5QI/C9ShczzlA7FG4HoXrOUAAAAAAAAA6QB+F61G4HjpAZmZmZmYmOkDhehSuR2E6QK5H4XoUbjpAuB6F61F4OkDD9Shcj4I6QArXo3A9ijpACtejcD2KOkAK16NwPYo6QM3MzMzMjDpA16NwPQqXOkCamZmZmZk6QOF6FK5HoTpApHA9CtejOkBxPQrXo7A6QA==",
            },
            y: [
              [
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
              ],
              [
                "  ระนอง",
                "  ยะลา",
                "  ชุมพร",
                "  สุราษฎร์ธานี",
                "  ตรัง",
                "  นราธิวาส",
                "  นครศรีธรรมราช",
                "  กระบี่",
                "  พังงา",
                "  สตูล",
                "  พัทลุง",
                "  สงขลา",
                "  ปัตตานี",
                "  ภูเก็ต",
                "  เลย",
                "  ชัยภูมิ",
                "  มุกดาหาร",
                "  นครพนม",
                "  สกลนคร",
                "  หนองบัวลำภู",
                "  บึงกาฬ",
                "  อุดรธานี",
                "  นครราชสีมา",
                "  กาฬสินธุ์",
                "  ขอนแก่น",
                "  หนองคาย",
                "  อำนาจเจริญ",
                "  บุรีรัมย์",
                "  ยโสธร",
                "  มหาสารคาม",
                "  ร้อยเอ็ด",
                "  อุบลราชธานี",
                "  สุรินทร์",
                "  ศรีสะเกษ",
                "  แม่ฮ่องสอน",
                "  เชียงใหม่",
                "  น่าน",
                "  ตาก",
                "  เชียงราย",
                "  พะเยา",
                "  ลำพูน",
                "  ลำปาง",
                "  แพร่",
                "  เพชรบูรณ์",
                "  อุตรดิตถ์",
                "  พิษณุโลก",
                "  กำแพงเพชร",
                "  อุทัยธานี",
                "  สุโขทัย",
                "  นครสวรรค์",
                "  พิจิตร",
                "  จันทบุรี",
                "  กาญจนบุรี",
                "  ประจวบคีรีขันธ์",
                "  ตราด",
                "  เพชรบุรี",
                "  สระแก้ว",
                "  นครนายก",
                "  ราชบุรี",
                "  ระยอง",
                "  ลพบุรี",
                "  ปราจีนบุรี",
                "  สระบุรี",
                "  ชลบุรี",
                "  สมุทรสงคราม",
                "  ฉะเชิงเทรา",
                "  สุพรรณบุรี",
                "  สมุทรปราการ",
                "  กรุงเทพมหานคร",
                "  ปทุมธานี",
                "  ชัยนาท",
                "  นนทบุรี",
                "  พระนครศรีอยุธยา",
                "  นครปฐม",
                "  สิงห์บุรี",
                "  อ่างทอง",
                "  สมุทรสาคร",
              ],
            ],
            type: "scatter",
          },
        ]}
        layout={{
          template: {
            data: {
              barpolar: [
                {
                  marker: {
                    line: {
                      color: "white",
                      width: 0.5,
                    },
                    pattern: {
                      fillmode: "overlay",
                      size: 10,
                      solidity: 0.2,
                    },
                  },
                  type: "barpolar",
                },
              ],
              bar: [
                {
                  error_x: {
                    color: "#2a3f5f",
                  },
                  error_y: {
                    color: "#2a3f5f",
                  },
                  marker: {
                    line: {
                      color: "white",
                      width: 0.5,
                    },
                    pattern: {
                      fillmode: "overlay",
                      size: 10,
                      solidity: 0.2,
                    },
                  },
                  type: "bar",
                },
              ],
              carpet: [
                {
                  aaxis: {
                    endlinecolor: "#2a3f5f",
                    gridcolor: "#C8D4E3",
                    linecolor: "#C8D4E3",
                    minorgridcolor: "#C8D4E3",
                    startlinecolor: "#2a3f5f",
                  },
                  baxis: {
                    endlinecolor: "#2a3f5f",
                    gridcolor: "#C8D4E3",
                    linecolor: "#C8D4E3",
                    minorgridcolor: "#C8D4E3",
                    startlinecolor: "#2a3f5f",
                  },
                  type: "carpet",
                },
              ],
              choropleth: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  type: "choropleth",
                },
              ],
              contourcarpet: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  type: "contourcarpet",
                },
              ],
              contour: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  colorscale: [
                    [0.0, "#0d0887"],
                    [0.1111111111111111, "#46039f"],
                    [0.2222222222222222, "#7201a8"],
                    [0.3333333333333333, "#9c179e"],
                    [0.4444444444444444, "#bd3786"],
                    [0.5555555555555556, "#d8576b"],
                    [0.6666666666666666, "#ed7953"],
                    [0.7777777777777778, "#fb9f3a"],
                    [0.8888888888888888, "#fdca26"],
                    [1.0, "#f0f921"],
                  ],
                  type: "contour",
                },
              ],
              heatmap: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  colorscale: [
                    [0.0, "#0d0887"],
                    [0.1111111111111111, "#46039f"],
                    [0.2222222222222222, "#7201a8"],
                    [0.3333333333333333, "#9c179e"],
                    [0.4444444444444444, "#bd3786"],
                    [0.5555555555555556, "#d8576b"],
                    [0.6666666666666666, "#ed7953"],
                    [0.7777777777777778, "#fb9f3a"],
                    [0.8888888888888888, "#fdca26"],
                    [1.0, "#f0f921"],
                  ],
                  type: "heatmap",
                },
              ],
              histogram2dcontour: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  colorscale: [
                    [0.0, "#0d0887"],
                    [0.1111111111111111, "#46039f"],
                    [0.2222222222222222, "#7201a8"],
                    [0.3333333333333333, "#9c179e"],
                    [0.4444444444444444, "#bd3786"],
                    [0.5555555555555556, "#d8576b"],
                    [0.6666666666666666, "#ed7953"],
                    [0.7777777777777778, "#fb9f3a"],
                    [0.8888888888888888, "#fdca26"],
                    [1.0, "#f0f921"],
                  ],
                  type: "histogram2dcontour",
                },
              ],
              histogram2d: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  colorscale: [
                    [0.0, "#0d0887"],
                    [0.1111111111111111, "#46039f"],
                    [0.2222222222222222, "#7201a8"],
                    [0.3333333333333333, "#9c179e"],
                    [0.4444444444444444, "#bd3786"],
                    [0.5555555555555556, "#d8576b"],
                    [0.6666666666666666, "#ed7953"],
                    [0.7777777777777778, "#fb9f3a"],
                    [0.8888888888888888, "#fdca26"],
                    [1.0, "#f0f921"],
                  ],
                  type: "histogram2d",
                },
              ],
              histogram: [
                {
                  marker: {
                    pattern: {
                      fillmode: "overlay",
                      size: 10,
                      solidity: 0.2,
                    },
                  },
                  type: "histogram",
                },
              ],
              mesh3d: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  type: "mesh3d",
                },
              ],
              parcoords: [
                {
                  line: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "parcoords",
                },
              ],
              pie: [
                {
                  automargin: true,
                  type: "pie",
                },
              ],
              scatter3d: [
                {
                  line: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scatter3d",
                },
              ],
              scattercarpet: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scattercarpet",
                },
              ],
              scattergeo: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scattergeo",
                },
              ],
              scattergl: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scattergl",
                },
              ],
              scattermapbox: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scattermapbox",
                },
              ],
              scattermap: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scattermap",
                },
              ],
              scatterpolargl: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scatterpolargl",
                },
              ],
              scatterpolar: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scatterpolar",
                },
              ],
              scatter: [
                {
                  fillpattern: {
                    fillmode: "overlay",
                    size: 10,
                    solidity: 0.2,
                  },
                  type: "scatter",
                },
              ],
              scatterternary: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scatterternary",
                },
              ],
              surface: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  colorscale: [
                    [0.0, "#0d0887"],
                    [0.1111111111111111, "#46039f"],
                    [0.2222222222222222, "#7201a8"],
                    [0.3333333333333333, "#9c179e"],
                    [0.4444444444444444, "#bd3786"],
                    [0.5555555555555556, "#d8576b"],
                    [0.6666666666666666, "#ed7953"],
                    [0.7777777777777778, "#fb9f3a"],
                    [0.8888888888888888, "#fdca26"],
                    [1.0, "#f0f921"],
                  ],
                  type: "surface",
                },
              ],
              table: [
                {
                  cells: {
                    fill: {
                      color: "#EBF0F8",
                    },
                    line: {
                      color: "white",
                    },
                  },
                  header: {
                    fill: {
                      color: "#C8D4E3",
                    },
                    line: {
                      color: "white",
                    },
                  },
                  type: "table",
                },
              ],
            },
            layout: {
              annotationdefaults: {
                arrowcolor: "#2a3f5f",
                arrowhead: 0,
                arrowwidth: 1,
              },
              autotypenumbers: "strict",
              coloraxis: {
                colorbar: {
                  outlinewidth: 0,
                  ticks: "",
                },
              },
              colorscale: {
                diverging: [
                  [0, "#8e0152"],
                  [0.1, "#c51b7d"],
                  [0.2, "#de77ae"],
                  [0.3, "#f1b6da"],
                  [0.4, "#fde0ef"],
                  [0.5, "#f7f7f7"],
                  [0.6, "#e6f5d0"],
                  [0.7, "#b8e186"],
                  [0.8, "#7fbc41"],
                  [0.9, "#4d9221"],
                  [1, "#276419"],
                ],
                sequential: [
                  [0.0, "#0d0887"],
                  [0.1111111111111111, "#46039f"],
                  [0.2222222222222222, "#7201a8"],
                  [0.3333333333333333, "#9c179e"],
                  [0.4444444444444444, "#bd3786"],
                  [0.5555555555555556, "#d8576b"],
                  [0.6666666666666666, "#ed7953"],
                  [0.7777777777777778, "#fb9f3a"],
                  [0.8888888888888888, "#fdca26"],
                  [1.0, "#f0f921"],
                ],
                sequentialminus: [
                  [0.0, "#0d0887"],
                  [0.1111111111111111, "#46039f"],
                  [0.2222222222222222, "#7201a8"],
                  [0.3333333333333333, "#9c179e"],
                  [0.4444444444444444, "#bd3786"],
                  [0.5555555555555556, "#d8576b"],
                  [0.6666666666666666, "#ed7953"],
                  [0.7777777777777778, "#fb9f3a"],
                  [0.8888888888888888, "#fdca26"],
                  [1.0, "#f0f921"],
                ],
              },
              colorway: [
                "#636efa",
                "#EF553B",
                "#00cc96",
                "#ab63fa",
                "#FFA15A",
                "#19d3f3",
                "#FF6692",
                "#B6E880",
                "#FF97FF",
                "#FECB52",
              ],
              font: {
                color: "#2a3f5f",
              },
              geo: {
                bgcolor: "white",
                lakecolor: "white",
                landcolor: "white",
                showlakes: true,
                showland: true,
                subunitcolor: "#C8D4E3",
              },
              hoverlabel: {
                align: "left",
              },
              hovermode: "closest",
              mapbox: {
                style: "light",
              },
              paper_bgcolor: "white",
              plot_bgcolor: "white",
              polar: {
                angularaxis: {
                  gridcolor: "#EBF0F8",
                  linecolor: "#EBF0F8",
                  ticks: "",
                },
                bgcolor: "white",
                radialaxis: {
                  gridcolor: "#EBF0F8",
                  linecolor: "#EBF0F8",
                  ticks: "",
                },
              },
              scene: {
                xaxis: {
                  backgroundcolor: "white",
                  gridcolor: "#DFE8F3",
                  gridwidth: 2,
                  linecolor: "#EBF0F8",
                  showbackground: true,
                  ticks: "",
                  zerolinecolor: "#EBF0F8",
                },
                yaxis: {
                  backgroundcolor: "white",
                  gridcolor: "#DFE8F3",
                  gridwidth: 2,
                  linecolor: "#EBF0F8",
                  showbackground: true,
                  ticks: "",
                  zerolinecolor: "#EBF0F8",
                },
                zaxis: {
                  backgroundcolor: "white",
                  gridcolor: "#DFE8F3",
                  gridwidth: 2,
                  linecolor: "#EBF0F8",
                  showbackground: true,
                  ticks: "",
                  zerolinecolor: "#EBF0F8",
                },
              },
              shapedefaults: {
                line: {
                  color: "#2a3f5f",
                },
              },
              ternary: {
                aaxis: {
                  gridcolor: "#DFE8F3",
                  linecolor: "#A2B1C6",
                  ticks: "",
                },
                baxis: {
                  gridcolor: "#DFE8F3",
                  linecolor: "#A2B1C6",
                  ticks: "",
                },
                bgcolor: "white",
                caxis: {
                  gridcolor: "#DFE8F3",
                  linecolor: "#A2B1C6",
                  ticks: "",
                },
              },
              title: {
                x: 0.05,
              },
              xaxis: {
                automargin: true,
                gridcolor: "#EBF0F8",
                linecolor: "#EBF0F8",
                ticks: "",
                title: {
                  standoff: 15,
                },
                zerolinecolor: "#EBF0F8",
                zerolinewidth: 2,
              },
              yaxis: {
                automargin: true,
                gridcolor: "#EBF0F8",
                linecolor: "#EBF0F8",
                ticks: "",
                title: {
                  standoff: 15,
                },
                zerolinecolor: "#EBF0F8",
                zerolinewidth: 2,
              },
            },
          },
          xaxis: {
            title: {
              font: {
                size: 18,
                color: "black",
              },
              text: "",
            },
            tickfont: {
              size: 16,
              color: "black",
            },
            automargin: true,
          },
          yaxis: {
            title: {
              font: {
                size: 18,
                color: "black",
              },
              text: "",
            },
            tickfont: {
              size: 10,
              color: "black",
            },
            categoryorder: "trace",
            automargin: true,
            domain: [0, 1],
            showgrid: false,
            showdividers: false,
            showline: false,
            ticks: "",
            range: [-0.5, 76.5],
            autorange: false,
          },
          legend: {
            font: {
              size: 18,
              color: "black",
            },
            title: {
              text: "",
            },
            orientation: "h",
            yanchor: "bottom",
            y: 1.0,
            xanchor: "right",
            x: 1,
          },
          plot_bgcolor: "white",
          paper_bgcolor: "white",
          hovermode: "closest",
          shapes: [
            {
              line: {
                color: "darkgrey",
                width: 2,
              },
              opacity: 1,
              type: "line",
              x0: -0.5,
              x1: 1,
              xref: "paper",
              y0: -0.5,
              y1: -0.5,
              yref: "y",
            },
            {
              line: {
                color: "darkgrey",
                width: 2,
              },
              opacity: 1,
              type: "line",
              x0: -0.5,
              x1: 1,
              xref: "paper",
              y0: 13.5,
              y1: 13.5,
              yref: "y",
            },
            {
              line: {
                color: "darkgrey",
                width: 2,
              },
              opacity: 1,
              type: "line",
              x0: -0.5,
              x1: 1,
              xref: "paper",
              y0: 33.5,
              y1: 33.5,
              yref: "y",
            },
            {
              line: {
                color: "darkgrey",
                width: 2,
              },
              opacity: 1,
              type: "line",
              x0: -0.5,
              x1: 1,
              xref: "paper",
              y0: 50.5,
              y1: 50.5,
              yref: "y",
            },
            {
              line: {
                color: "darkgrey",
                width: 2,
              },
              opacity: 1,
              type: "line",
              x0: -0.5,
              x1: 1,
              xref: "paper",
              y0: 76.5,
              y1: 76.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: -0.5,
              y1: 0.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 1.5,
              y1: 2.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 3.5,
              y1: 4.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 5.5,
              y1: 6.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 7.5,
              y1: 8.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 9.5,
              y1: 10.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 11.5,
              y1: 12.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 13.5,
              y1: 14.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 15.5,
              y1: 16.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 17.5,
              y1: 18.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 19.5,
              y1: 20.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 21.5,
              y1: 22.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 23.5,
              y1: 24.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 25.5,
              y1: 26.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 27.5,
              y1: 28.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 29.5,
              y1: 30.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 31.5,
              y1: 32.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 33.5,
              y1: 34.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 35.5,
              y1: 36.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 37.5,
              y1: 38.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 39.5,
              y1: 40.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 41.5,
              y1: 42.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 43.5,
              y1: 44.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 45.5,
              y1: 46.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 47.5,
              y1: 48.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 49.5,
              y1: 50.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 51.5,
              y1: 52.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 53.5,
              y1: 54.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 55.5,
              y1: 56.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 57.5,
              y1: 58.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 59.5,
              y1: 60.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 61.5,
              y1: 62.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 63.5,
              y1: 64.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 65.5,
              y1: 66.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 67.5,
              y1: 68.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 69.5,
              y1: 70.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 71.5,
              y1: 72.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 73.5,
              y1: 74.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 75.5,
              y1: 76.5,
              yref: "y",
            },
          ],
          title: {
            text: "",
          },
          margin: {
            l: 200,
            r: 50,
            t: 50,
            b: 80,
          },
          height: 1200,
          width: 800,
          annotations: [
            {
              align: "center",
              font: {
                color: "black",
                size: 24,
              },
              showarrow: false,
              text: "<b>Baseline</b>",
              x: 0.28,
              xanchor: "center",
              xref: "paper",
              y: -0.03,
              yanchor: "top",
              yref: "paper",
            },
          ],
        }}
      />
    </div>
  )
}
