import React from "react"
import { LazyPlotly } from "../../../../src/components/Plots"

export default function Ab202516Fig4B1() {
  return (
    <div style={{ clear: "both", marginBottom: "20px" }}>
      <LazyPlotly
        data={[
          {
            error_x: {
              array: {
                dtype: "f8",
                bdata:
                  "sEfhehSeYUAAAAAAACx3QAAQrkfhetQ/4HoUrkcBa0DMzMzMzBRxQKhwPQrXK2FA1qNwPQrxh0A4MzMzM1NmQNijcD0Kb2BAIIXrUbiuXUD2KFyPwlWHQJDC9Shcl2tASOF6FK7HaUAoXI/C9YBpQIAUrkfhujZA/P////8vbkCkcD0K19NsQLBH4XoUrkRAQArXo3AtWECQwvUoXAN0QDwK16NwdXhAoJmZmZl5QUAM16NwPWpgQEjhehSup2dA4HoUrkdhOUDA9ShcjzJcQEAK16Nw5XBAfBSuR+HqaUBQuB6F69FaQAjXo3A9smVAhutRuB49cUCE61G4Hs1qQEAK16NwFWJAFK5H4XqIdUDYo3A9CjdUQBSuR+F61GJAFK5H4XoceEDYo3A9CvdTQLBH4XoU7lNAgBSuR+HKV0BSuB6F60FwQOB6FK5HkW5AQOF6FK43XUAI16NwPcJkQChcj8L11HZAehSuR+GWeECwR+F6FM5uQFyPwvUolItAZGZmZmZWc0AM16NwPSCDQGZmZmZmFoFAwMzMzMxMKUAAAAAAAMBEQAjXo3A9ql1A0MzMzMysQ0Bgj8L1KDxNQCCuR+F6VDFAAK5H4XoUDkAghetRuN49QBCF61G4vkZAsEfhehQOTUAAAAAAAAAAAEAK16NwXUBAkML1KFzfUkCkcD0K1/9yQAQAAAAAoGBAAgAAAAD4fECI61G4HpVlQCCF61G43l1AiOtRuB5VckD4KFyPwv1tQGCPwvUofGVAYI/C9Sh8T0BI4XoUrs9iQHgUrkfhCm1A9ihcj8KngUBI4XoUrm93QA==",
              },
              arrayminus: {
                dtype: "f8",
                bdata:
                  "KFyPwvWAZkCocD0K19tlQADAHoXrUcg/4HoUrkdRVECQwvUoXNdmQOB6FK5HgWNAaGZmZmYCdkDA9Shcj9JaQPgoXI/CBWRA8Chcj8KdYkAAAAAAAExzQAjXo3A96mpAIIXrUbi+bUCI61G4HrVtQKDC9ShcDzZAKFyPwvWIVEAYhetRuJ5VQOBRuB6Fi0RAIIXrUbj+WUA0MzMzM3NjQFyPwvUoPGZAoEfhehRuM0Bcj8L1KPxgQKBwPQrXi2BA4KNwPQoXO0AAAAAAAPBWQEThehSut2FAkML1KFyPXUCYmZmZmclTQDAzMzMzI11A4HoUrkchWkAUrkfhesxhQKxH4XoUtmFAth6F61FsdkAAAAAAAMBMQAjXo3A9elFAuB6F61EIY0DgehSuR6FUQFC4HoXr2WBA6FG4HoXrUkCsR+F6FJ5iQAjXo3A9cmRAuB6F61GoYkDE9Shcj+JlQPQoXI/CrWtAULgeheu5bkBE4XoUrrdrQJiZmZmZ0XZAvB6F61FgbUDgehSuRw1yQLoehetREHxAwPUoXI+CNUCAPQrXo/BKQHA9CtejMEdAsB6F61G4SUDAzMzMzGxIQACuR+F6VDFAAK5H4XoUFEDgehSuR+E9QBDXo3A9+lBAcD0K16PwUkAAAAAAAAAAADAzMzMzo1ZAiML1KFw/VUAI16NwPQJiQEAK16NwHU1A6FG4HoVLbkBE4XoUrsdiQNCjcD0KR1BACNejcD3aYECwR+F6FI5dQEDhehSul1pAgBSuR+E6SkDgehSuR1lrQEAK16NwfWxAOArXo3BdbkAghetRuPJ0QA==",
              },
              color: "#1f77b4",
              symmetric: false,
              thickness: 1,
              type: "data",
              width: 2,
            },
            hovertemplate: "<b>%{y}</b><br>mean: %{x:.2f}<extra></extra>",
            marker: {
              color: "#1f77b4",
              size: 10,
            },
            mode: "markers",
            name: "Historical",
            opacity: 0.8,
            x: {
              dtype: "f8",
              bdata:
                "4XoUrkevkUBxPQrXo3GTQOxRuB6FhZNAuB6F61GSlECuR+F6FA6VQOF6FK5HhJVAcT0K16ONlUAzMzMzM46VQIXrUbgenZVA4XoUrkfwlUDXo3A9CnGWQM3MzMzMl5ZA9ihcj8KXmEBI4XoUrvaaQClcj8L1dohAcT0K16N0iUA9CtejcIOJQI/C9ShcVYpAexSuR+Eei0CamZmZmT2LQFK4HoXrV4tAj8L1KFxji0BmZmZmZqiLQBSuR+F6BoxAzczMzMwwjEDD9ShcjziMQBSuR+F6ZIxAcT0K16OsjEBmZmZmZuKMQK5H4XoUHo9A16NwPQofj0BxPQrXo2SPQOF6FK5H8JBAj8L1KFwWk0D2KFyPwgOIQM3MzMzMKopAUrgehesHi0DNzMzMzI6LQFyPwvUonoxAj8L1KFyrjEA9CtejcLuMQGZmZmZm2IxAUrgehesVjUBSuB6F67mOQAAAAAAA3o5AhetRuB5bj0DhehSuR6KQQGZmZmZmL5FA9ihcj8JAkUAUrkfheoGRQB+F61G4JZVA16NwPQoViUDsUbgehTmJQHsUrkfhtIlAFK5H4XoAikC4HoXrUUaKQI/C9ShccYpAXI/C9Sgki0AAAAAAAEKLQOxRuB6Fj4tAuB6F61HYi0AfhetRuOqMQFK4HoXr74xAFK5H4XpIjUC4HoXrUbiOQOF6FK5HGY9APQrXo3B9j0A9CtejcGCQQArXo3A9cpBAj8L1KFz3kEAzMzMzM66SQNejcD0KaJNAexSuR+FblEAfhetRuF6UQJqZmZmZ4pRAuB6F61F7lkBcj8L1KBqeQA==",
            },
            y: [
              [
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
              ],
              [
                "  ปัตตานี",
                "  นราธิวาส",
                "  ภูเก็ต",
                "  กระบี่",
                "  สุราษฎร์ธานี",
                "  สตูล",
                "  ยะลา",
                "  ตรัง",
                "  พัทลุง",
                "  ชุมพร",
                "  สงขลา",
                "  นครศรีธรรมราช",
                "  พังงา",
                "  ระนอง",
                "  มหาสารคาม",
                "  ขอนแก่น",
                "  อุดรธานี",
                "  ร้อยเอ็ด",
                "  หนองบัวลำภู",
                "  ชัยภูมิ",
                "  นครราชสีมา",
                "  ยโสธร",
                "  หนองคาย",
                "  สกลนคร",
                "  อำนาจเจริญ",
                "  สุรินทร์",
                "  บุรีรัมย์",
                "  กาฬสินธุ์",
                "  ศรีสะเกษ",
                "  มุกดาหาร",
                "  อุบลราชธานี",
                "  เลย",
                "  นครพนม",
                "  บึงกาฬ",
                "  พิจิตร",
                "  สุโขทัย",
                "  นครสวรรค์",
                "  แพร่",
                "  ลำพูน",
                "  พะเยา",
                "  เชียงราย",
                "  พิษณุโลก",
                "  อุตรดิตถ์",
                "  ลำปาง",
                "  อุทัยธานี",
                "  เชียงใหม่",
                "  เพชรบูรณ์",
                "  กำแพงเพชร",
                "  แม่ฮ่องสอน",
                "  น่าน",
                "  ตาก",
                "  สมุทรสาคร",
                "  ชัยนาท",
                "  สุพรรณบุรี",
                "  นครปฐม",
                "  ลพบุรี",
                "  สิงห์บุรี",
                "  อ่างทอง",
                "  สมุทรปราการ",
                "  นนทบุรี",
                "  กรุงเทพมหานคร",
                "  สมุทรสงคราม",
                "  ปทุมธานี",
                "  พระนครศรีอยุธยา",
                "  ราชบุรี",
                "  สระบุรี",
                "  กาญจนบุรี",
                "  สระแก้ว",
                "  ฉะเชิงเทรา",
                "  เพชรบุรี",
                "  ประจวบคีรีขันธ์",
                "  ชลบุรี",
                "  ระยอง",
                "  นครนายก",
                "  ปราจีนบุรี",
                "  จันทบุรี",
                "  ตราด",
              ],
            ],
            type: "scatter",
          },
          {
            error_x: {
              array: {
                dtype: "f8",
                bdata:
                  "YI/C9SgsYUAAzszMzMwGQNDMzMzM+HJA0MzMzMysYECgcD0K17NYQLgehetRUGRAehSuR+FghkAwMzMzM4NrQAAAAAAAIFRAYI/C9SjsXEAUrkfhekCIQEAK16Nw1WdAcD0K16OcdEDwKFyPwuVfQIAUrkfhGkJAPArXo3C9aUBUuB6F64FnQMD1KFyPIkBAZmZmZmbadUAI16NwPQpZQFC4HoXryWVAIFyPwvWoNkBgj8L1KCxbQKBH4XoUbjZAqHA9CtfzVEAI16NwPYZ1QJiZmZmZSVpA2KNwPQq3aUBQuB6F61lsQAAAAAAA+GVAnJmZmZn5bkCsR+F6FIZqQHA9CtejIF9AuB6F61HIckA4MzMzM4NWQML1KFyPbndAMDMzMzOLY0AoXI/C9YBtQHI9CtejcHVAEK5H4Xr0UEBwZmZmZvZcQAjXo3A9Wl5AkML1KFyvbkDA9ShcjyJaQEjhehSuN2pAeBSuR+Hib0AchetRuP50QArXo3A9sIhAnJmZmZnFfEAchetRuB50QITrUbge84FAMDMzMzNzQkDQo3A9CndLQMBH4XoULi5A4HoUrkfhX0AAhetRuB4HQAAghetRuL4/YLgeheuxTEDgo3A9Ctc3QLBH4XoUjlRAQArXo3CdRUCgwvUoXA88QEAK16NwfUBAIIXrUbg2YUBYj8L1KDRgQEjhehSuD2VAcD0K16OofkAAAAAAAAAAAJDC9Shck3JAULgehet1cEDA9Shcj/pnQFi4HoXr6WRAIIXrUbgeYUBgj8L1KPxsQCDXo3A9qkhAhOtRuB7lfkB8FK5H4UJ1QA==",
              },
              arrayminus: {
                dtype: "f8",
                bdata:
                  "eBSuR+EiZkAAeBSuR+H6P8jMzMzMLGNAgOtRuB6lVEB4FK5H4RpjQLBH4XoUzllAfBSuR+GSdEBgj8L1KLRkQIjrUbgeRWJAaGZmZmYGZEDE9Shcj8p2QHA9CtejYG1A0MzMzMzEakCQwvUoXLdkQKBwPQrXIzpA0MzMzMxsUkDQo3A9CrdNQCCF61G4/kJAULgehevRXECQwvUoXF9ZQAAAAAAAcF1AwJmZmZmZK0BkZmZmZn5gQMBH4XoULjxAIIXrUbgOUUCI61G4HiVjQAjXo3A9ilVAyMzMzMysXkAQrkfhemRcQMj1KFyPIlxASOF6FK6XVUDYo3A9CidiQDAzMzMze2FAhutRuB59c0BACtejcJ1MQPgoXI/CxV5A2KNwPQp3UkBI4XoUrn9kQCCF61G49mtA+Chcj8K1X0AI16NwPbpTQDQzMzMzS2RApHA9CtdrZUBI4XoUrrdWQCCF61G4TmJAnJmZmZlZb0BM4XoUrt9vQAzXo3A9nnVAZmZmZmYCcEB8FK5H4dJrQFS4HoXrGXxAIIXrUbi+RUAgrkfhetRFQIBH4XoULi5AkOtRuB5FTUAAj8L1KFwBQACgmZmZmck/cBSuR+G6RECgmZmZmdk3QFC4HoXrsVFA+Chcj8KVUUDQzMzMzPxRQOhRuB6FW1JA8Chcj8I1S0DwUbgehUtSQMT1KFyPCmFAiOtRuB7FbUAAAAAAAAAAAJDC9Shcn2VA0MzMzMykYUAAAAAAADBjQAAAAAAAGGpAIFyPwvWYV0BACtejcB1sQAAAAAAAYERAIIXrUbgGbkA8CtejcFFzQA==",
              },
              color: "#d62728",
              symmetric: false,
              thickness: 1,
              type: "data",
              width: 2,
            },
            hovertemplate: "<b>%{y}</b><br>mean: %{x:.2f}<extra></extra>",
            marker: {
              color: "#d62728",
              size: 10,
            },
            mode: "markers",
            name: "Projected",
            opacity: 0.8,
            x: {
              dtype: "f8",
              bdata:
                "hetRuB5UkEA9CtejcN2QQD0K16NwSJJAKVyPwvWwkkCF61G4HlaTQClcj8L1YpNAexSuR+F4k0CkcD0K1/uTQKRwPQrXXJRACtejcD11lECkcD0K1xaVQNejcD0Kb5VAUrgeheuTlUCkcD0K16CXQHsUrkfhqIdAmpmZmZm9h0A9CtejcDeIQOxRuB6F/YhA16NwPQqNiUD2KFyPwpWJQKRwPQrX5YlA7FG4HoUlikCPwvUoXDuKQHsUrkfhpopArkfhehTAikD2KFyPwsuKQKRwPQrX0YpAFK5H4XryikAK16NwPS6LQJqZmZmZ0YxAH4XrUbhmjUCF61G4Hp2NQBSuR+F6po5ASOF6FK5zkUC4HoXrUdCIQM3MzMzMEIpA7FG4HoXPikAK16NwPUiNQClcj8L1yo1AmpmZmZkfjkBmZmZmZkSOQClcj8L1iI5AZmZmZmbKjkBSuB6F602PQM3MzMzMYJBAw/UoXI9qkEDD9Shcj6uQQMP1KFyPVpFACtejcD0hkkBI4XoUrkmSQB+F61G4XZVAmpmZmZn7h0BI4XoUrjOIQBSuR+F6cohAH4XrUbiyiECuR+F6FNSIQNejcD0KMYlAPQrXo3AhikDNzMzMzECKQAAAAAAA9opAH4XrUbhki0CuR+F6FN6LQAAAAAAABoxAXI/C9SjajEDsUbgehUWOQKRwPQrXf45ASOF6FK4ikEAK16NwPUuQQFK4HoXrlJBAcT0K16NnkkDNzMzMzJKSQOF6FK5HTZNAhetRuB5vk0AAAAAAAKeTQLgehetRL5RASOF6FK7VlUApXI/C9cObQA==",
            },
            y: [
              [
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
              ],
              [
                "  ปัตตานี",
                "  ภูเก็ต",
                "  นราธิวาส",
                "  กระบี่",
                "  สตูล",
                "  ตรัง",
                "  ยะลา",
                "  สุราษฎร์ธานี",
                "  พัทลุง",
                "  ชุมพร",
                "  สงขลา",
                "  พังงา",
                "  นครศรีธรรมราช",
                "  ระนอง",
                "  มหาสารคาม",
                "  อุดรธานี",
                "  ขอนแก่น",
                "  ร้อยเอ็ด",
                "  นครราชสีมา",
                "  หนองบัวลำภู",
                "  สกลนคร",
                "  ยโสธร",
                "  หนองคาย",
                "  อำนาจเจริญ",
                "  ศรีสะเกษ",
                "  ชัยภูมิ",
                "  สุรินทร์",
                "  กาฬสินธุ์",
                "  บุรีรัมย์",
                "  มุกดาหาร",
                "  อุบลราชธานี",
                "  เลย",
                "  นครพนม",
                "  บึงกาฬ",
                "  พิจิตร",
                "  นครสวรรค์",
                "  สุโขทัย",
                "  พิษณุโลก",
                "  อุทัยธานี",
                "  ลำพูน",
                "  แพร่",
                "  อุตรดิตถ์",
                "  เชียงราย",
                "  พะเยา",
                "  ลำปาง",
                "  เพชรบูรณ์",
                "  เชียงใหม่",
                "  กำแพงเพชร",
                "  น่าน",
                "  แม่ฮ่องสอน",
                "  ตาก",
                "  ชัยนาท",
                "  ลพบุรี",
                "  สิงห์บุรี",
                "  สุพรรณบุรี",
                "  อ่างทอง",
                "  สมุทรสาคร",
                "  นครปฐม",
                "  สมุทรปราการ",
                "  พระนครศรีอยุธยา",
                "  กรุงเทพมหานคร",
                "  นนทบุรี",
                "  ปทุมธานี",
                "  สระบุรี",
                "  ฉะเชิงเทรา",
                "  สระแก้ว",
                "  กาญจนบุรี",
                "  สมุทรสงคราม",
                "  ราชบุรี",
                "  เพชรบุรี",
                "  ชลบุรี",
                "  นครนายก",
                "  ประจวบคีรีขันธ์",
                "  ปราจีนบุรี",
                "  ระยอง",
                "  จันทบุรี",
                "  ตราด",
              ],
            ],
            type: "scatter",
          },
        ]}
        layout={{
          template: {
            data: {
              barpolar: [
                {
                  marker: {
                    line: {
                      color: "white",
                      width: 0.5,
                    },
                    pattern: {
                      fillmode: "overlay",
                      size: 10,
                      solidity: 0.2,
                    },
                  },
                  type: "barpolar",
                },
              ],
              bar: [
                {
                  error_x: {
                    color: "#2a3f5f",
                  },
                  error_y: {
                    color: "#2a3f5f",
                  },
                  marker: {
                    line: {
                      color: "white",
                      width: 0.5,
                    },
                    pattern: {
                      fillmode: "overlay",
                      size: 10,
                      solidity: 0.2,
                    },
                  },
                  type: "bar",
                },
              ],
              carpet: [
                {
                  aaxis: {
                    endlinecolor: "#2a3f5f",
                    gridcolor: "#C8D4E3",
                    linecolor: "#C8D4E3",
                    minorgridcolor: "#C8D4E3",
                    startlinecolor: "#2a3f5f",
                  },
                  baxis: {
                    endlinecolor: "#2a3f5f",
                    gridcolor: "#C8D4E3",
                    linecolor: "#C8D4E3",
                    minorgridcolor: "#C8D4E3",
                    startlinecolor: "#2a3f5f",
                  },
                  type: "carpet",
                },
              ],
              choropleth: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  type: "choropleth",
                },
              ],
              contourcarpet: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  type: "contourcarpet",
                },
              ],
              contour: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  colorscale: [
                    [0.0, "#0d0887"],
                    [0.1111111111111111, "#46039f"],
                    [0.2222222222222222, "#7201a8"],
                    [0.3333333333333333, "#9c179e"],
                    [0.4444444444444444, "#bd3786"],
                    [0.5555555555555556, "#d8576b"],
                    [0.6666666666666666, "#ed7953"],
                    [0.7777777777777778, "#fb9f3a"],
                    [0.8888888888888888, "#fdca26"],
                    [1.0, "#f0f921"],
                  ],
                  type: "contour",
                },
              ],
              heatmap: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  colorscale: [
                    [0.0, "#0d0887"],
                    [0.1111111111111111, "#46039f"],
                    [0.2222222222222222, "#7201a8"],
                    [0.3333333333333333, "#9c179e"],
                    [0.4444444444444444, "#bd3786"],
                    [0.5555555555555556, "#d8576b"],
                    [0.6666666666666666, "#ed7953"],
                    [0.7777777777777778, "#fb9f3a"],
                    [0.8888888888888888, "#fdca26"],
                    [1.0, "#f0f921"],
                  ],
                  type: "heatmap",
                },
              ],
              histogram2dcontour: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  colorscale: [
                    [0.0, "#0d0887"],
                    [0.1111111111111111, "#46039f"],
                    [0.2222222222222222, "#7201a8"],
                    [0.3333333333333333, "#9c179e"],
                    [0.4444444444444444, "#bd3786"],
                    [0.5555555555555556, "#d8576b"],
                    [0.6666666666666666, "#ed7953"],
                    [0.7777777777777778, "#fb9f3a"],
                    [0.8888888888888888, "#fdca26"],
                    [1.0, "#f0f921"],
                  ],
                  type: "histogram2dcontour",
                },
              ],
              histogram2d: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  colorscale: [
                    [0.0, "#0d0887"],
                    [0.1111111111111111, "#46039f"],
                    [0.2222222222222222, "#7201a8"],
                    [0.3333333333333333, "#9c179e"],
                    [0.4444444444444444, "#bd3786"],
                    [0.5555555555555556, "#d8576b"],
                    [0.6666666666666666, "#ed7953"],
                    [0.7777777777777778, "#fb9f3a"],
                    [0.8888888888888888, "#fdca26"],
                    [1.0, "#f0f921"],
                  ],
                  type: "histogram2d",
                },
              ],
              histogram: [
                {
                  marker: {
                    pattern: {
                      fillmode: "overlay",
                      size: 10,
                      solidity: 0.2,
                    },
                  },
                  type: "histogram",
                },
              ],
              mesh3d: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  type: "mesh3d",
                },
              ],
              parcoords: [
                {
                  line: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "parcoords",
                },
              ],
              pie: [
                {
                  automargin: true,
                  type: "pie",
                },
              ],
              scatter3d: [
                {
                  line: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scatter3d",
                },
              ],
              scattercarpet: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scattercarpet",
                },
              ],
              scattergeo: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scattergeo",
                },
              ],
              scattergl: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scattergl",
                },
              ],
              scattermapbox: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scattermapbox",
                },
              ],
              scattermap: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scattermap",
                },
              ],
              scatterpolargl: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scatterpolargl",
                },
              ],
              scatterpolar: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scatterpolar",
                },
              ],
              scatter: [
                {
                  fillpattern: {
                    fillmode: "overlay",
                    size: 10,
                    solidity: 0.2,
                  },
                  type: "scatter",
                },
              ],
              scatterternary: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scatterternary",
                },
              ],
              surface: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  colorscale: [
                    [0.0, "#0d0887"],
                    [0.1111111111111111, "#46039f"],
                    [0.2222222222222222, "#7201a8"],
                    [0.3333333333333333, "#9c179e"],
                    [0.4444444444444444, "#bd3786"],
                    [0.5555555555555556, "#d8576b"],
                    [0.6666666666666666, "#ed7953"],
                    [0.7777777777777778, "#fb9f3a"],
                    [0.8888888888888888, "#fdca26"],
                    [1.0, "#f0f921"],
                  ],
                  type: "surface",
                },
              ],
              table: [
                {
                  cells: {
                    fill: {
                      color: "#EBF0F8",
                    },
                    line: {
                      color: "white",
                    },
                  },
                  header: {
                    fill: {
                      color: "#C8D4E3",
                    },
                    line: {
                      color: "white",
                    },
                  },
                  type: "table",
                },
              ],
            },
            layout: {
              annotationdefaults: {
                arrowcolor: "#2a3f5f",
                arrowhead: 0,
                arrowwidth: 1,
              },
              autotypenumbers: "strict",
              coloraxis: {
                colorbar: {
                  outlinewidth: 0,
                  ticks: "",
                },
              },
              colorscale: {
                diverging: [
                  [0, "#8e0152"],
                  [0.1, "#c51b7d"],
                  [0.2, "#de77ae"],
                  [0.3, "#f1b6da"],
                  [0.4, "#fde0ef"],
                  [0.5, "#f7f7f7"],
                  [0.6, "#e6f5d0"],
                  [0.7, "#b8e186"],
                  [0.8, "#7fbc41"],
                  [0.9, "#4d9221"],
                  [1, "#276419"],
                ],
                sequential: [
                  [0.0, "#0d0887"],
                  [0.1111111111111111, "#46039f"],
                  [0.2222222222222222, "#7201a8"],
                  [0.3333333333333333, "#9c179e"],
                  [0.4444444444444444, "#bd3786"],
                  [0.5555555555555556, "#d8576b"],
                  [0.6666666666666666, "#ed7953"],
                  [0.7777777777777778, "#fb9f3a"],
                  [0.8888888888888888, "#fdca26"],
                  [1.0, "#f0f921"],
                ],
                sequentialminus: [
                  [0.0, "#0d0887"],
                  [0.1111111111111111, "#46039f"],
                  [0.2222222222222222, "#7201a8"],
                  [0.3333333333333333, "#9c179e"],
                  [0.4444444444444444, "#bd3786"],
                  [0.5555555555555556, "#d8576b"],
                  [0.6666666666666666, "#ed7953"],
                  [0.7777777777777778, "#fb9f3a"],
                  [0.8888888888888888, "#fdca26"],
                  [1.0, "#f0f921"],
                ],
              },
              colorway: [
                "#636efa",
                "#EF553B",
                "#00cc96",
                "#ab63fa",
                "#FFA15A",
                "#19d3f3",
                "#FF6692",
                "#B6E880",
                "#FF97FF",
                "#FECB52",
              ],
              font: {
                color: "#2a3f5f",
              },
              geo: {
                bgcolor: "white",
                lakecolor: "white",
                landcolor: "white",
                showlakes: true,
                showland: true,
                subunitcolor: "#C8D4E3",
              },
              hoverlabel: {
                align: "left",
              },
              hovermode: "closest",
              mapbox: {
                style: "light",
              },
              paper_bgcolor: "white",
              plot_bgcolor: "white",
              polar: {
                angularaxis: {
                  gridcolor: "#EBF0F8",
                  linecolor: "#EBF0F8",
                  ticks: "",
                },
                bgcolor: "white",
                radialaxis: {
                  gridcolor: "#EBF0F8",
                  linecolor: "#EBF0F8",
                  ticks: "",
                },
              },
              scene: {
                xaxis: {
                  backgroundcolor: "white",
                  gridcolor: "#DFE8F3",
                  gridwidth: 2,
                  linecolor: "#EBF0F8",
                  showbackground: true,
                  ticks: "",
                  zerolinecolor: "#EBF0F8",
                },
                yaxis: {
                  backgroundcolor: "white",
                  gridcolor: "#DFE8F3",
                  gridwidth: 2,
                  linecolor: "#EBF0F8",
                  showbackground: true,
                  ticks: "",
                  zerolinecolor: "#EBF0F8",
                },
                zaxis: {
                  backgroundcolor: "white",
                  gridcolor: "#DFE8F3",
                  gridwidth: 2,
                  linecolor: "#EBF0F8",
                  showbackground: true,
                  ticks: "",
                  zerolinecolor: "#EBF0F8",
                },
              },
              shapedefaults: {
                line: {
                  color: "#2a3f5f",
                },
              },
              ternary: {
                aaxis: {
                  gridcolor: "#DFE8F3",
                  linecolor: "#A2B1C6",
                  ticks: "",
                },
                baxis: {
                  gridcolor: "#DFE8F3",
                  linecolor: "#A2B1C6",
                  ticks: "",
                },
                bgcolor: "white",
                caxis: {
                  gridcolor: "#DFE8F3",
                  linecolor: "#A2B1C6",
                  ticks: "",
                },
              },
              title: {
                x: 0.05,
              },
              xaxis: {
                automargin: true,
                gridcolor: "#EBF0F8",
                linecolor: "#EBF0F8",
                ticks: "",
                title: {
                  standoff: 15,
                },
                zerolinecolor: "#EBF0F8",
                zerolinewidth: 2,
              },
              yaxis: {
                automargin: true,
                gridcolor: "#EBF0F8",
                linecolor: "#EBF0F8",
                ticks: "",
                title: {
                  standoff: 15,
                },
                zerolinecolor: "#EBF0F8",
                zerolinewidth: 2,
              },
            },
          },
          xaxis: {
            title: {
              font: {
                size: 18,
                color: "black",
              },
              text: "",
            },
            tickfont: {
              size: 16,
              color: "black",
            },
            automargin: true,
          },
          yaxis: {
            title: {
              font: {
                size: 18,
                color: "black",
              },
              text: "",
            },
            tickfont: {
              size: 10,
              color: "black",
            },
            categoryorder: "trace",
            automargin: true,
            domain: [0, 1],
            showgrid: false,
            showdividers: false,
            showline: false,
            ticks: "",
            range: [-0.5, 76.5],
            autorange: false,
          },
          legend: {
            font: {
              size: 18,
              color: "black",
            },
            title: {
              text: "",
            },
            orientation: "h",
            yanchor: "bottom",
            y: 1.0,
            xanchor: "right",
            x: 1,
          },
          plot_bgcolor: "white",
          paper_bgcolor: "white",
          hovermode: "closest",
          shapes: [
            {
              line: {
                color: "darkgrey",
                width: 2,
              },
              opacity: 1,
              type: "line",
              x0: -0.5,
              x1: 1,
              xref: "paper",
              y0: -0.5,
              y1: -0.5,
              yref: "y",
            },
            {
              line: {
                color: "darkgrey",
                width: 2,
              },
              opacity: 1,
              type: "line",
              x0: -0.5,
              x1: 1,
              xref: "paper",
              y0: 13.5,
              y1: 13.5,
              yref: "y",
            },
            {
              line: {
                color: "darkgrey",
                width: 2,
              },
              opacity: 1,
              type: "line",
              x0: -0.5,
              x1: 1,
              xref: "paper",
              y0: 33.5,
              y1: 33.5,
              yref: "y",
            },
            {
              line: {
                color: "darkgrey",
                width: 2,
              },
              opacity: 1,
              type: "line",
              x0: -0.5,
              x1: 1,
              xref: "paper",
              y0: 50.5,
              y1: 50.5,
              yref: "y",
            },
            {
              line: {
                color: "darkgrey",
                width: 2,
              },
              opacity: 1,
              type: "line",
              x0: -0.5,
              x1: 1,
              xref: "paper",
              y0: 76.5,
              y1: 76.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: -0.5,
              y1: 0.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 1.5,
              y1: 2.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 3.5,
              y1: 4.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 5.5,
              y1: 6.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 7.5,
              y1: 8.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 9.5,
              y1: 10.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 11.5,
              y1: 12.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 13.5,
              y1: 14.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 15.5,
              y1: 16.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 17.5,
              y1: 18.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 19.5,
              y1: 20.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 21.5,
              y1: 22.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 23.5,
              y1: 24.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 25.5,
              y1: 26.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 27.5,
              y1: 28.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 29.5,
              y1: 30.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 31.5,
              y1: 32.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 33.5,
              y1: 34.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 35.5,
              y1: 36.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 37.5,
              y1: 38.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 39.5,
              y1: 40.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 41.5,
              y1: 42.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 43.5,
              y1: 44.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 45.5,
              y1: 46.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 47.5,
              y1: 48.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 49.5,
              y1: 50.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 51.5,
              y1: 52.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 53.5,
              y1: 54.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 55.5,
              y1: 56.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 57.5,
              y1: 58.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 59.5,
              y1: 60.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 61.5,
              y1: 62.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 63.5,
              y1: 64.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 65.5,
              y1: 66.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 67.5,
              y1: 68.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 69.5,
              y1: 70.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 71.5,
              y1: 72.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 73.5,
              y1: 74.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 75.5,
              y1: 76.5,
              yref: "y",
            },
          ],
          title: {
            text: "",
          },
          margin: {
            l: 200,
            r: 50,
            t: 50,
            b: 80,
          },
          height: 1200,
          width: 800,
          annotations: [
            {
              align: "center",
              font: {
                color: "black",
                size: 24,
              },
              showarrow: false,
              text: "<b>Baseline</b>",
              x: 0.28,
              xanchor: "center",
              xref: "paper",
              y: -0.03,
              yanchor: "top",
              yref: "paper",
            },
          ],
        }}
      />
    </div>
  )
}
