import React from "react"
import { LazyPlotly } from "../../../../src/components/Plots"

export default function Ab202516Fig4B3() {
  return (
    <div style={{ clear: "both", marginBottom: "20px" }}>
      <LazyPlotly
        data={[
          {
            error_x: {
              array: {
                dtype: "f8",
                bdata:
                  "OB4S6an85D/cNB2yot31PzxkmNVon/E/jJsOqJ7GB0DwWuZm+gP+P4GJevWRQRlAyObMPPO+D0CQdHgA9SkcQBCBV3f9qfs/IBaS2yU48z+gbTY5JZ/TP741HMVTwhpAoH39F7O3DkBkPkWJdz0QQDAH4FiW8wtAQMQcOx3hC0BMpFeCRLkTQHwUDbA1Wvw/UPfwcZEw6D/olx2arZ/0P9CHpToURO8/RHU7tFC/9z+AQEyHFdb5P0wkpa4VOvY/1GKZlvv88z8cP4AIyHfwP7AXd0vDdQFABHwtV61P9T8gIFdDfsjiP0iTH6KPPfk/XGHWQ0yGBUCoenNfnuAFQFCbd8rOmPg/gE0avlJb7T+mbUavv0kDQMqUyIcKaQVAIjB0fi+7EECgwho1Z4X6P6gI5Q5Pd/U/qsJdVkMyE0DoFQbKvMnwPxhFI3wS6fg/XJj8RtJIAUDyFkHnb4YQQFCIf+rZtvI/jLPFBnyYAkBUhtSf/OYEQLx/nxZj/QRAuE4t1AAAFUBu9sPECLEwQEXE9hjFEyVAaNz5HLqt0j9gXHgZwM/cP3zRKusNavk/yGQ51OY25j+AKNM6in2nP5B86ckRDf4/ZBhYXOl78j/YPJJgbzoJQID4BAJLmcE/APzoGHa8mD84yhbMSyfmP7h01ez4sek/hGoPM/HxAkBKTN7z5SwDQFCpmPH+DwdAgPNxTLt67z/4Yc/v2BcJQACAQmnqLjK/Ux0VAN05EUAyRQ7nv+UYQEg0aJudIvM/ANdHZncvHECkew8SB60FQGK2NH/qxxBAsISpoIPe+z9oXMqqNI4YQA==",
              },
              arrayminus: {
                dtype: "f8",
                bdata:
                  "4Ppkbwzs1j8InAUpV6H0P7iZPKOAh/E//qVRPTJcBEDUNJ0kPLIAQICt1bYhMwZAYHXChQJqBEDGErnw6PkEQPR+iaK7dABA0GatWTiC+j+AmSamuRfHP1K3om/X5QlADJ9cTIgnAUDQHA+Hqh4HQM7562otffs/pn1HHwnJ/D8prXlXBlACQHwUT9+Mm/o/6BLmMd8M6j/YMoSrCFT7PxDzbnMznec/iFeRGHwN8z8sB5Xz/tfxP7BCIorQNe0/FMSXcbAf+D/glfjgXrnzPwi4DRNr5/I/7AAS3rBq/j8wFzL+4RzmP3xiCbr/hPI/fMaU2EzE+z+ch1h2Ifn9P0R9jIs/lP0/4OuZCiRj5j8cYFLxDQT4P6rTyGVy1gBABqwZLiigCUC4SxJ9Nmr9P3T7cP/dOvQ/UBYJdCkOC0Bsohi7LojzPxCAkKtLa+w/xBd2Ib+kAUBwtSPN5BMAQMj6QODHjvc/QNIou36N+D9AxHmbALH+PyhRg8SWgQtAiBG4/CFbFUAwFaP9BPcgQPCLwBVX0xpAoDRe66ET4z+USAKTOsfuP2wqfwbF4/Y/UIYa76Ck1j+AoKODFZ2nP541tCWWufM/j751l8G1AEAKPoJN2KYEQKA6LjHomcE/AGLRMJZFkj/w0TjOzhfaP1w5k158EPA/svOqFhsQAkCMF7aAxZP+P2yEco0/6vg/UIV32nWN7D+4LTRusOD3PwCAQmnqLjI/miW70GhnAECu+KP8IXoHQIhEgYuT5fw/msCCttFrDEBmW5ReNl0HQHydbaWbrQZAkIUtA+1e9D/YAxsm7kwYQA==",
              },
              color: "green",
              symmetric: false,
              thickness: 0.5,
              type: "data",
              width: 2,
            },
            hovertemplate: "<b>%{y}</b><br>mean: %{x:.3f}<extra></extra>",
            marker: {
              color: "green",
              size: 10,
            },
            mode: "markers",
            name: "Difference (Projected - Historical)",
            opacity: 0.8,
            x: {
              dtype: "f8",
              bdata:
                "31ei4xrTFkB1z9K30mcaQK1bLeMpbhxAbLqkyAqBHkBemCOLBwAfQOky+p2GQh9A/jg1wjDNIEBuucFUflQhQJQDEyY5tCFA1lYn3pQyIkAYOIiOJegkQOGvE2OMUiVA6lgfv/4jKEBGSoRsTM0pQIisAjzGcxNA3nLqS5hAFECCU/xgYeIUQNFiw9+p8hVA/wfz2ZmWFkAW8rFN3c4YQEWECTPHIxlAc0OhRZQhG0Cej0fNV68bQCmWpiES4BtATdLgMJrPHEBBnPxXch0dQKKI8qH/vx1Aiw0cpr4dH0A4++TEh5UfQGTaiNgapSBAX1sIxOXHIEB/fbIqzjAhQGUEBQqMCCNAUbetlkBTI0APRHHWZ7wZQNeUa0kSuhtAwAqhOucMIEAd5Wbw9l8gQNew2zybvCBAv8wYNln7IEAMtH0G45UhQCyPz5ODviFA+1wBOW3zIUDdgoy+ZewjQJCoSVy+wiRAADnqwgEKJUCc5rb0mqomQKDiTWMD0ClAvFw/pCwyLEDnCKHSfSAuQMlou4QqlC9AT77fJgUfD0B5r8a4TT8RQEW8co9TyRFAlIUWFct/EkD/5iFaF9QTQAconGaK9BNA3SJGOMjWFEB+COhXdP8UQKATz/fCChZAaFLG2dB+FkBMP4HcJOgWQGGlSIhcDhdAUDj1pTzlF0DRAm2VT18YQFRVJVpOWhxAlkIH2jP9HECCudT8poweQN3yC8yguR5AZQFw63T+H0BC1/d23IEgQAjnD4zhOSFAxJ9INEASIkDmGNAeZHAiQLv2Hd+PhyZAg9NAmly2KkDuFGov13czQA==",
            },
            y: [
              [
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคใต้</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคตะวันออกเฉียงเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคเหนือ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
                "<span style='font-size: 16px; font-weight: bold;'>ภาคกลาง</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
              ],
              [
                "  ปัตตานี",
                "  นราธิวาส",
                "  พัทลุง",
                "  ชุมพร",
                "  สุราษฎร์ธานี",
                "  ยะลา",
                "  ตรัง",
                "  สงขลา",
                "  นครศรีธรรมราช",
                "  สตูล",
                "  ภูเก็ต",
                "  กระบี่",
                "  ระนอง",
                "  พังงา",
                "  บุรีรัมย์",
                "  ชัยภูมิ",
                "  นครราชสีมา",
                "  ขอนแก่น",
                "  หนองบัวลำภู",
                "  สุรินทร์",
                "  มหาสารคาม",
                "  เลย",
                "  ร้อยเอ็ด",
                "  ยโสธร",
                "  ศรีสะเกษ",
                "  อุบลราชธานี",
                "  อุดรธานี",
                "  หนองคาย",
                "  อำนาจเจริญ",
                "  กาฬสินธุ์",
                "  สกลนคร",
                "  นครพนม",
                "  บึงกาฬ",
                "  มุกดาหาร",
                "  ลำพูน",
                "  นครสวรรค์",
                "  เพชรบูรณ์",
                "  พิจิตร",
                "  เชียงราย",
                "  เชียงใหม่",
                "  อุทัยธานี",
                "  ลำปาง",
                "  พะเยา",
                "  พิษณุโลก",
                "  แพร่",
                "  สุโขทัย",
                "  กำแพงเพชร",
                "  อุตรดิตถ์",
                "  น่าน",
                "  ตาก",
                "  แม่ฮ่องสอน",
                "  ปทุมธานี",
                "  นนทบุรี",
                "  นครปฐม",
                "  กรุงเทพมหานคร",
                "  สมุทรปราการ",
                "  ฉะเชิงเทรา",
                "  พระนครศรีอยุธยา",
                "  สุพรรณบุรี",
                "  สิงห์บุรี",
                "  อ่างทอง",
                "  สมุทรสาคร",
                "  ลพบุรี",
                "  สระบุรี",
                "  สระแก้ว",
                "  ชลบุรี",
                "  ชัยนาท",
                "  ปราจีนบุรี",
                "  สมุทรสงคราม",
                "  ราชบุรี",
                "  กาญจนบุรี",
                "  ระยอง",
                "  จันทบุรี",
                "  นครนายก",
                "  ประจวบคีรีขันธ์",
                "  เพชรบุรี",
                "  ตราด",
              ],
            ],
            type: "scatter",
          },
        ]}
        layout={{
          template: {
            data: {
              barpolar: [
                {
                  marker: {
                    line: {
                      color: "white",
                      width: 0.5,
                    },
                    pattern: {
                      fillmode: "overlay",
                      size: 10,
                      solidity: 0.2,
                    },
                  },
                  type: "barpolar",
                },
              ],
              bar: [
                {
                  error_x: {
                    color: "#2a3f5f",
                  },
                  error_y: {
                    color: "#2a3f5f",
                  },
                  marker: {
                    line: {
                      color: "white",
                      width: 0.5,
                    },
                    pattern: {
                      fillmode: "overlay",
                      size: 10,
                      solidity: 0.2,
                    },
                  },
                  type: "bar",
                },
              ],
              carpet: [
                {
                  aaxis: {
                    endlinecolor: "#2a3f5f",
                    gridcolor: "#C8D4E3",
                    linecolor: "#C8D4E3",
                    minorgridcolor: "#C8D4E3",
                    startlinecolor: "#2a3f5f",
                  },
                  baxis: {
                    endlinecolor: "#2a3f5f",
                    gridcolor: "#C8D4E3",
                    linecolor: "#C8D4E3",
                    minorgridcolor: "#C8D4E3",
                    startlinecolor: "#2a3f5f",
                  },
                  type: "carpet",
                },
              ],
              choropleth: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  type: "choropleth",
                },
              ],
              contourcarpet: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  type: "contourcarpet",
                },
              ],
              contour: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  colorscale: [
                    [0.0, "#0d0887"],
                    [0.1111111111111111, "#46039f"],
                    [0.2222222222222222, "#7201a8"],
                    [0.3333333333333333, "#9c179e"],
                    [0.4444444444444444, "#bd3786"],
                    [0.5555555555555556, "#d8576b"],
                    [0.6666666666666666, "#ed7953"],
                    [0.7777777777777778, "#fb9f3a"],
                    [0.8888888888888888, "#fdca26"],
                    [1.0, "#f0f921"],
                  ],
                  type: "contour",
                },
              ],
              heatmap: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  colorscale: [
                    [0.0, "#0d0887"],
                    [0.1111111111111111, "#46039f"],
                    [0.2222222222222222, "#7201a8"],
                    [0.3333333333333333, "#9c179e"],
                    [0.4444444444444444, "#bd3786"],
                    [0.5555555555555556, "#d8576b"],
                    [0.6666666666666666, "#ed7953"],
                    [0.7777777777777778, "#fb9f3a"],
                    [0.8888888888888888, "#fdca26"],
                    [1.0, "#f0f921"],
                  ],
                  type: "heatmap",
                },
              ],
              histogram2dcontour: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  colorscale: [
                    [0.0, "#0d0887"],
                    [0.1111111111111111, "#46039f"],
                    [0.2222222222222222, "#7201a8"],
                    [0.3333333333333333, "#9c179e"],
                    [0.4444444444444444, "#bd3786"],
                    [0.5555555555555556, "#d8576b"],
                    [0.6666666666666666, "#ed7953"],
                    [0.7777777777777778, "#fb9f3a"],
                    [0.8888888888888888, "#fdca26"],
                    [1.0, "#f0f921"],
                  ],
                  type: "histogram2dcontour",
                },
              ],
              histogram2d: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  colorscale: [
                    [0.0, "#0d0887"],
                    [0.1111111111111111, "#46039f"],
                    [0.2222222222222222, "#7201a8"],
                    [0.3333333333333333, "#9c179e"],
                    [0.4444444444444444, "#bd3786"],
                    [0.5555555555555556, "#d8576b"],
                    [0.6666666666666666, "#ed7953"],
                    [0.7777777777777778, "#fb9f3a"],
                    [0.8888888888888888, "#fdca26"],
                    [1.0, "#f0f921"],
                  ],
                  type: "histogram2d",
                },
              ],
              histogram: [
                {
                  marker: {
                    pattern: {
                      fillmode: "overlay",
                      size: 10,
                      solidity: 0.2,
                    },
                  },
                  type: "histogram",
                },
              ],
              mesh3d: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  type: "mesh3d",
                },
              ],
              parcoords: [
                {
                  line: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "parcoords",
                },
              ],
              pie: [
                {
                  automargin: true,
                  type: "pie",
                },
              ],
              scatter3d: [
                {
                  line: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scatter3d",
                },
              ],
              scattercarpet: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scattercarpet",
                },
              ],
              scattergeo: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scattergeo",
                },
              ],
              scattergl: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scattergl",
                },
              ],
              scattermapbox: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scattermapbox",
                },
              ],
              scattermap: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scattermap",
                },
              ],
              scatterpolargl: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scatterpolargl",
                },
              ],
              scatterpolar: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scatterpolar",
                },
              ],
              scatter: [
                {
                  fillpattern: {
                    fillmode: "overlay",
                    size: 10,
                    solidity: 0.2,
                  },
                  type: "scatter",
                },
              ],
              scatterternary: [
                {
                  marker: {
                    colorbar: {
                      outlinewidth: 0,
                      ticks: "",
                    },
                  },
                  type: "scatterternary",
                },
              ],
              surface: [
                {
                  colorbar: {
                    outlinewidth: 0,
                    ticks: "",
                  },
                  colorscale: [
                    [0.0, "#0d0887"],
                    [0.1111111111111111, "#46039f"],
                    [0.2222222222222222, "#7201a8"],
                    [0.3333333333333333, "#9c179e"],
                    [0.4444444444444444, "#bd3786"],
                    [0.5555555555555556, "#d8576b"],
                    [0.6666666666666666, "#ed7953"],
                    [0.7777777777777778, "#fb9f3a"],
                    [0.8888888888888888, "#fdca26"],
                    [1.0, "#f0f921"],
                  ],
                  type: "surface",
                },
              ],
              table: [
                {
                  cells: {
                    fill: {
                      color: "#EBF0F8",
                    },
                    line: {
                      color: "white",
                    },
                  },
                  header: {
                    fill: {
                      color: "#C8D4E3",
                    },
                    line: {
                      color: "white",
                    },
                  },
                  type: "table",
                },
              ],
            },
            layout: {
              annotationdefaults: {
                arrowcolor: "#2a3f5f",
                arrowhead: 0,
                arrowwidth: 1,
              },
              autotypenumbers: "strict",
              coloraxis: {
                colorbar: {
                  outlinewidth: 0,
                  ticks: "",
                },
              },
              colorscale: {
                diverging: [
                  [0, "#8e0152"],
                  [0.1, "#c51b7d"],
                  [0.2, "#de77ae"],
                  [0.3, "#f1b6da"],
                  [0.4, "#fde0ef"],
                  [0.5, "#f7f7f7"],
                  [0.6, "#e6f5d0"],
                  [0.7, "#b8e186"],
                  [0.8, "#7fbc41"],
                  [0.9, "#4d9221"],
                  [1, "#276419"],
                ],
                sequential: [
                  [0.0, "#0d0887"],
                  [0.1111111111111111, "#46039f"],
                  [0.2222222222222222, "#7201a8"],
                  [0.3333333333333333, "#9c179e"],
                  [0.4444444444444444, "#bd3786"],
                  [0.5555555555555556, "#d8576b"],
                  [0.6666666666666666, "#ed7953"],
                  [0.7777777777777778, "#fb9f3a"],
                  [0.8888888888888888, "#fdca26"],
                  [1.0, "#f0f921"],
                ],
                sequentialminus: [
                  [0.0, "#0d0887"],
                  [0.1111111111111111, "#46039f"],
                  [0.2222222222222222, "#7201a8"],
                  [0.3333333333333333, "#9c179e"],
                  [0.4444444444444444, "#bd3786"],
                  [0.5555555555555556, "#d8576b"],
                  [0.6666666666666666, "#ed7953"],
                  [0.7777777777777778, "#fb9f3a"],
                  [0.8888888888888888, "#fdca26"],
                  [1.0, "#f0f921"],
                ],
              },
              colorway: [
                "#636efa",
                "#EF553B",
                "#00cc96",
                "#ab63fa",
                "#FFA15A",
                "#19d3f3",
                "#FF6692",
                "#B6E880",
                "#FF97FF",
                "#FECB52",
              ],
              font: {
                color: "#2a3f5f",
              },
              geo: {
                bgcolor: "white",
                lakecolor: "white",
                landcolor: "white",
                showlakes: true,
                showland: true,
                subunitcolor: "#C8D4E3",
              },
              hoverlabel: {
                align: "left",
              },
              hovermode: "closest",
              mapbox: {
                style: "light",
              },
              paper_bgcolor: "white",
              plot_bgcolor: "white",
              polar: {
                angularaxis: {
                  gridcolor: "#EBF0F8",
                  linecolor: "#EBF0F8",
                  ticks: "",
                },
                bgcolor: "white",
                radialaxis: {
                  gridcolor: "#EBF0F8",
                  linecolor: "#EBF0F8",
                  ticks: "",
                },
              },
              scene: {
                xaxis: {
                  backgroundcolor: "white",
                  gridcolor: "#DFE8F3",
                  gridwidth: 2,
                  linecolor: "#EBF0F8",
                  showbackground: true,
                  ticks: "",
                  zerolinecolor: "#EBF0F8",
                },
                yaxis: {
                  backgroundcolor: "white",
                  gridcolor: "#DFE8F3",
                  gridwidth: 2,
                  linecolor: "#EBF0F8",
                  showbackground: true,
                  ticks: "",
                  zerolinecolor: "#EBF0F8",
                },
                zaxis: {
                  backgroundcolor: "white",
                  gridcolor: "#DFE8F3",
                  gridwidth: 2,
                  linecolor: "#EBF0F8",
                  showbackground: true,
                  ticks: "",
                  zerolinecolor: "#EBF0F8",
                },
              },
              shapedefaults: {
                line: {
                  color: "#2a3f5f",
                },
              },
              ternary: {
                aaxis: {
                  gridcolor: "#DFE8F3",
                  linecolor: "#A2B1C6",
                  ticks: "",
                },
                baxis: {
                  gridcolor: "#DFE8F3",
                  linecolor: "#A2B1C6",
                  ticks: "",
                },
                bgcolor: "white",
                caxis: {
                  gridcolor: "#DFE8F3",
                  linecolor: "#A2B1C6",
                  ticks: "",
                },
              },
              title: {
                x: 0.05,
              },
              xaxis: {
                automargin: true,
                gridcolor: "#EBF0F8",
                linecolor: "#EBF0F8",
                ticks: "",
                title: {
                  standoff: 15,
                },
                zerolinecolor: "#EBF0F8",
                zerolinewidth: 2,
              },
              yaxis: {
                automargin: true,
                gridcolor: "#EBF0F8",
                linecolor: "#EBF0F8",
                ticks: "",
                title: {
                  standoff: 15,
                },
                zerolinecolor: "#EBF0F8",
                zerolinewidth: 2,
              },
            },
          },
          xaxis: {
            title: {
              font: {
                size: 18,
                color: "black",
              },
              text: "",
            },
            tickfont: {
              size: 16,
              color: "black",
            },
            automargin: true,
            zeroline: false,
            range: [0, 34.9305],
            rangemode: "tozero",
            zerolinewidth: 1,
            zerolinecolor: "black",
          },
          yaxis: {
            title: {
              font: {
                size: 18,
                color: "black",
              },
              text: "",
            },
            tickfont: {
              size: 10,
              color: "black",
            },
            categoryorder: "trace",
            automargin: true,
            domain: [0, 1],
            showgrid: false,
            showdividers: false,
            showline: false,
            ticks: "",
            range: [-0.5, 76.5],
            autorange: false,
          },
          legend: {
            font: {
              size: 18,
              color: "black",
            },
            title: {
              text: "",
            },
            orientation: "h",
            yanchor: "bottom",
            y: 1.0,
            xanchor: "right",
            x: 1,
          },
          plot_bgcolor: "white",
          paper_bgcolor: "white",
          title: {
            text: "",
          },
          showlegend: true,
          hovermode: "closest",
          shapes: [
            {
              line: {
                color: "darkgrey",
                width: 2,
              },
              opacity: 1,
              type: "line",
              x0: -0.5,
              x1: 1,
              xref: "paper",
              y0: -0.5,
              y1: -0.5,
              yref: "y",
            },
            {
              line: {
                color: "darkgrey",
                width: 2,
              },
              opacity: 1,
              type: "line",
              x0: -0.5,
              x1: 1,
              xref: "paper",
              y0: 13.5,
              y1: 13.5,
              yref: "y",
            },
            {
              line: {
                color: "darkgrey",
                width: 2,
              },
              opacity: 1,
              type: "line",
              x0: -0.5,
              x1: 1,
              xref: "paper",
              y0: 33.5,
              y1: 33.5,
              yref: "y",
            },
            {
              line: {
                color: "darkgrey",
                width: 2,
              },
              opacity: 1,
              type: "line",
              x0: -0.5,
              x1: 1,
              xref: "paper",
              y0: 50.5,
              y1: 50.5,
              yref: "y",
            },
            {
              line: {
                color: "darkgrey",
                width: 2,
              },
              opacity: 1,
              type: "line",
              x0: -0.5,
              x1: 1,
              xref: "paper",
              y0: 76.5,
              y1: 76.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: -0.5,
              y1: 0.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 1.5,
              y1: 2.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 3.5,
              y1: 4.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 5.5,
              y1: 6.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 7.5,
              y1: 8.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 9.5,
              y1: 10.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 11.5,
              y1: 12.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 13.5,
              y1: 14.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 15.5,
              y1: 16.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 17.5,
              y1: 18.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 19.5,
              y1: 20.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 21.5,
              y1: 22.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 23.5,
              y1: 24.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 25.5,
              y1: 26.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 27.5,
              y1: 28.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 29.5,
              y1: 30.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 31.5,
              y1: 32.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 33.5,
              y1: 34.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 35.5,
              y1: 36.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 37.5,
              y1: 38.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 39.5,
              y1: 40.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 41.5,
              y1: 42.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 43.5,
              y1: 44.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 45.5,
              y1: 46.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 47.5,
              y1: 48.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 49.5,
              y1: 50.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 51.5,
              y1: 52.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 53.5,
              y1: 54.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 55.5,
              y1: 56.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 57.5,
              y1: 58.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 59.5,
              y1: 60.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 61.5,
              y1: 62.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 63.5,
              y1: 64.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 65.5,
              y1: 66.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 67.5,
              y1: 68.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 69.5,
              y1: 70.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 71.5,
              y1: 72.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 73.5,
              y1: 74.5,
              yref: "y",
            },
            {
              fillcolor: "rgba(200, 200, 200, 0.2)",
              layer: "below",
              line: {
                width: 0,
              },
              type: "rect",
              x0: -0.15,
              x1: 1,
              xref: "paper",
              y0: 75.5,
              y1: 76.5,
              yref: "y",
            },
          ],
          margin: {
            l: 200,
            r: 50,
            t: 50,
            b: 80,
          },
          height: 1200,
          width: 800,
          annotations: [
            {
              align: "center",
              font: {
                color: "black",
                size: 24,
              },
              showarrow: false,
              text: "<b>Δ Seasonality (Mean Absolute)</b>",
              x: 0.27,
              xanchor: "center",
              xref: "paper",
              y: -0.03,
              yanchor: "top",
              yref: "paper",
            },
          ],
        }}
      />
    </div>
  )
}
